// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/host.proto

package host

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifiedStatus int32

const (
	VerifiedStatus_PENDING  VerifiedStatus = 0
	VerifiedStatus_ONREVIEW VerifiedStatus = 1
	VerifiedStatus_ACCEPTED VerifiedStatus = 2
	VerifiedStatus_REJECTED VerifiedStatus = 3
)

var VerifiedStatus_name = map[int32]string{
	0: "PENDING",
	1: "ONREVIEW",
	2: "ACCEPTED",
	3: "REJECTED",
}

var VerifiedStatus_value = map[string]int32{
	"PENDING":  0,
	"ONREVIEW": 1,
	"ACCEPTED": 2,
	"REJECTED": 3,
}

func (x VerifiedStatus) String() string {
	return proto.EnumName(VerifiedStatus_name, int32(x))
}

func (VerifiedStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{0}
}

type TourHost struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender               string               `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Password             string               `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	BusinessName         string               `protobuf:"bytes,8,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessCategory     string               `protobuf:"bytes,9,opt,name=business_category,json=businessCategory,proto3" json:"business_category,omitempty"`
	Address              string               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	BusinessAbout        string               `protobuf:"bytes,11,opt,name=business_about,json=businessAbout,proto3" json:"business_about,omitempty"`
	PersonalidType       string               `protobuf:"bytes,12,opt,name=personalid_type,json=personalidType,proto3" json:"personalid_type,omitempty"`
	PersonalidNumber     string               `protobuf:"bytes,13,opt,name=personalid_number,json=personalidNumber,proto3" json:"personalid_number,omitempty"`
	VerificationType     string               `protobuf:"bytes,14,opt,name=verification_type,json=verificationType,proto3" json:"verification_type,omitempty"`
	VerificationNumber   string               `protobuf:"bytes,15,opt,name=verification_number,json=verificationNumber,proto3" json:"verification_number,omitempty"`
	IsVerified           bool                 `protobuf:"varint,16,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	AccountNumber        string               `protobuf:"bytes,17,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance              string               `protobuf:"bytes,18,opt,name=balance,proto3" json:"balance,omitempty"`
	UserUid              string               `protobuf:"bytes,19,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Email                string               `protobuf:"bytes,21,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TourHost) Reset()         { *m = TourHost{} }
func (m *TourHost) String() string { return proto.CompactTextString(m) }
func (*TourHost) ProtoMessage()    {}
func (*TourHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{0}
}

func (m *TourHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TourHost.Unmarshal(m, b)
}
func (m *TourHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TourHost.Marshal(b, m, deterministic)
}
func (m *TourHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TourHost.Merge(m, src)
}
func (m *TourHost) XXX_Size() int {
	return xxx_messageInfo_TourHost.Size(m)
}
func (m *TourHost) XXX_DiscardUnknown() {
	xxx_messageInfo_TourHost.DiscardUnknown(m)
}

var xxx_messageInfo_TourHost proto.InternalMessageInfo

func (m *TourHost) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *TourHost) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *TourHost) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *TourHost) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *TourHost) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *TourHost) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *TourHost) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TourHost) GetBusinessName() string {
	if m != nil {
		return m.BusinessName
	}
	return ""
}

func (m *TourHost) GetBusinessCategory() string {
	if m != nil {
		return m.BusinessCategory
	}
	return ""
}

func (m *TourHost) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TourHost) GetBusinessAbout() string {
	if m != nil {
		return m.BusinessAbout
	}
	return ""
}

func (m *TourHost) GetPersonalidType() string {
	if m != nil {
		return m.PersonalidType
	}
	return ""
}

func (m *TourHost) GetPersonalidNumber() string {
	if m != nil {
		return m.PersonalidNumber
	}
	return ""
}

func (m *TourHost) GetVerificationType() string {
	if m != nil {
		return m.VerificationType
	}
	return ""
}

func (m *TourHost) GetVerificationNumber() string {
	if m != nil {
		return m.VerificationNumber
	}
	return ""
}

func (m *TourHost) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *TourHost) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *TourHost) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *TourHost) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *TourHost) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TourHost) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateTourHostRequest struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string               `protobuf:"bytes,7,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	BusinessName         string               `protobuf:"bytes,8,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessCategory     string               `protobuf:"bytes,9,opt,name=business_category,json=businessCategory,proto3" json:"business_category,omitempty"`
	Address              string               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	BusinessAbout        string               `protobuf:"bytes,11,opt,name=business_about,json=businessAbout,proto3" json:"business_about,omitempty"`
	PersonalidType       string               `protobuf:"bytes,12,opt,name=personalid_type,json=personalidType,proto3" json:"personalid_type,omitempty"`
	PersonalidNumber     string               `protobuf:"bytes,13,opt,name=personalid_number,json=personalidNumber,proto3" json:"personalid_number,omitempty"`
	VerificationType     string               `protobuf:"bytes,14,opt,name=verification_type,json=verificationType,proto3" json:"verification_type,omitempty"`
	VerificationNumber   string               `protobuf:"bytes,15,opt,name=verification_number,json=verificationNumber,proto3" json:"verification_number,omitempty"`
	IsVerified           bool                 `protobuf:"varint,16,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	AccountNumber        string               `protobuf:"bytes,17,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance              string               `protobuf:"bytes,18,opt,name=balance,proto3" json:"balance,omitempty"`
	UserUid              string               `protobuf:"bytes,19,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Email                string               `protobuf:"bytes,21,opt,name=email,proto3" json:"email,omitempty"`
	Gender               string               `protobuf:"bytes,22,opt,name=gender,proto3" json:"gender,omitempty"`
	ByAdmin              bool                 `protobuf:"varint,23,opt,name=by_admin,json=byAdmin,proto3" json:"by_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateTourHostRequest) Reset()         { *m = UpdateTourHostRequest{} }
func (m *UpdateTourHostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTourHostRequest) ProtoMessage()    {}
func (*UpdateTourHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{1}
}

func (m *UpdateTourHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTourHostRequest.Unmarshal(m, b)
}
func (m *UpdateTourHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTourHostRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTourHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTourHostRequest.Merge(m, src)
}
func (m *UpdateTourHostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTourHostRequest.Size(m)
}
func (m *UpdateTourHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTourHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTourHostRequest proto.InternalMessageInfo

func (m *UpdateTourHostRequest) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *UpdateTourHostRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateTourHostRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateTourHostRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UpdateTourHostRequest) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *UpdateTourHostRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateTourHostRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *UpdateTourHostRequest) GetBusinessName() string {
	if m != nil {
		return m.BusinessName
	}
	return ""
}

func (m *UpdateTourHostRequest) GetBusinessCategory() string {
	if m != nil {
		return m.BusinessCategory
	}
	return ""
}

func (m *UpdateTourHostRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpdateTourHostRequest) GetBusinessAbout() string {
	if m != nil {
		return m.BusinessAbout
	}
	return ""
}

func (m *UpdateTourHostRequest) GetPersonalidType() string {
	if m != nil {
		return m.PersonalidType
	}
	return ""
}

func (m *UpdateTourHostRequest) GetPersonalidNumber() string {
	if m != nil {
		return m.PersonalidNumber
	}
	return ""
}

func (m *UpdateTourHostRequest) GetVerificationType() string {
	if m != nil {
		return m.VerificationType
	}
	return ""
}

func (m *UpdateTourHostRequest) GetVerificationNumber() string {
	if m != nil {
		return m.VerificationNumber
	}
	return ""
}

func (m *UpdateTourHostRequest) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *UpdateTourHostRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *UpdateTourHostRequest) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *UpdateTourHostRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *UpdateTourHostRequest) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *UpdateTourHostRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateTourHostRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UpdateTourHostRequest) GetByAdmin() bool {
	if m != nil {
		return m.ByAdmin
	}
	return false
}

type UpdateTourHostRespone struct {
	Data                 *UpdateTourHostRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title                string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpdateTourHostRespone) Reset()         { *m = UpdateTourHostRespone{} }
func (m *UpdateTourHostRespone) String() string { return proto.CompactTextString(m) }
func (*UpdateTourHostRespone) ProtoMessage()    {}
func (*UpdateTourHostRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{2}
}

func (m *UpdateTourHostRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTourHostRespone.Unmarshal(m, b)
}
func (m *UpdateTourHostRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTourHostRespone.Marshal(b, m, deterministic)
}
func (m *UpdateTourHostRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTourHostRespone.Merge(m, src)
}
func (m *UpdateTourHostRespone) XXX_Size() int {
	return xxx_messageInfo_UpdateTourHostRespone.Size(m)
}
func (m *UpdateTourHostRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTourHostRespone.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTourHostRespone proto.InternalMessageInfo

func (m *UpdateTourHostRespone) GetData() *UpdateTourHostRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateTourHostRespone) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UpdateTourHostRespone) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateTourHostRequest struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string               `protobuf:"bytes,7,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	BusinessName         string               `protobuf:"bytes,8,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessCategory     string               `protobuf:"bytes,9,opt,name=business_category,json=businessCategory,proto3" json:"business_category,omitempty"`
	Address              string               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	BusinessAbout        string               `protobuf:"bytes,11,opt,name=business_about,json=businessAbout,proto3" json:"business_about,omitempty"`
	PersonalidType       string               `protobuf:"bytes,12,opt,name=personalid_type,json=personalidType,proto3" json:"personalid_type,omitempty"`
	PersonalidNumber     string               `protobuf:"bytes,13,opt,name=personalid_number,json=personalidNumber,proto3" json:"personalid_number,omitempty"`
	VerificationType     string               `protobuf:"bytes,14,opt,name=verification_type,json=verificationType,proto3" json:"verification_type,omitempty"`
	VerificationNumber   string               `protobuf:"bytes,15,opt,name=verification_number,json=verificationNumber,proto3" json:"verification_number,omitempty"`
	IsVerified           bool                 `protobuf:"varint,16,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	AccountNumber        string               `protobuf:"bytes,17,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance              string               `protobuf:"bytes,18,opt,name=balance,proto3" json:"balance,omitempty"`
	UserUid              string               `protobuf:"bytes,19,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Email                string               `protobuf:"bytes,21,opt,name=email,proto3" json:"email,omitempty"`
	Gender               string               `protobuf:"bytes,22,opt,name=gender,proto3" json:"gender,omitempty"`
	ByAdmin              bool                 `protobuf:"varint,23,opt,name=by_admin,json=byAdmin,proto3" json:"by_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTourHostRequest) Reset()         { *m = CreateTourHostRequest{} }
func (m *CreateTourHostRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTourHostRequest) ProtoMessage()    {}
func (*CreateTourHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{3}
}

func (m *CreateTourHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTourHostRequest.Unmarshal(m, b)
}
func (m *CreateTourHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTourHostRequest.Marshal(b, m, deterministic)
}
func (m *CreateTourHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTourHostRequest.Merge(m, src)
}
func (m *CreateTourHostRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTourHostRequest.Size(m)
}
func (m *CreateTourHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTourHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTourHostRequest proto.InternalMessageInfo

func (m *CreateTourHostRequest) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *CreateTourHostRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateTourHostRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateTourHostRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateTourHostRequest) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *CreateTourHostRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateTourHostRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *CreateTourHostRequest) GetBusinessName() string {
	if m != nil {
		return m.BusinessName
	}
	return ""
}

func (m *CreateTourHostRequest) GetBusinessCategory() string {
	if m != nil {
		return m.BusinessCategory
	}
	return ""
}

func (m *CreateTourHostRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateTourHostRequest) GetBusinessAbout() string {
	if m != nil {
		return m.BusinessAbout
	}
	return ""
}

func (m *CreateTourHostRequest) GetPersonalidType() string {
	if m != nil {
		return m.PersonalidType
	}
	return ""
}

func (m *CreateTourHostRequest) GetPersonalidNumber() string {
	if m != nil {
		return m.PersonalidNumber
	}
	return ""
}

func (m *CreateTourHostRequest) GetVerificationType() string {
	if m != nil {
		return m.VerificationType
	}
	return ""
}

func (m *CreateTourHostRequest) GetVerificationNumber() string {
	if m != nil {
		return m.VerificationNumber
	}
	return ""
}

func (m *CreateTourHostRequest) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *CreateTourHostRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *CreateTourHostRequest) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *CreateTourHostRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *CreateTourHostRequest) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *CreateTourHostRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateTourHostRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *CreateTourHostRequest) GetByAdmin() bool {
	if m != nil {
		return m.ByAdmin
	}
	return false
}

type CreateTourHostRespone struct {
	Data                 *CreateTourHostRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title                string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateTourHostRespone) Reset()         { *m = CreateTourHostRespone{} }
func (m *CreateTourHostRespone) String() string { return proto.CompactTextString(m) }
func (*CreateTourHostRespone) ProtoMessage()    {}
func (*CreateTourHostRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{4}
}

func (m *CreateTourHostRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTourHostRespone.Unmarshal(m, b)
}
func (m *CreateTourHostRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTourHostRespone.Marshal(b, m, deterministic)
}
func (m *CreateTourHostRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTourHostRespone.Merge(m, src)
}
func (m *CreateTourHostRespone) XXX_Size() int {
	return xxx_messageInfo_CreateTourHostRespone.Size(m)
}
func (m *CreateTourHostRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTourHostRespone.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTourHostRespone proto.InternalMessageInfo

func (m *CreateTourHostRespone) GetData() *CreateTourHostRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateTourHostRespone) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateTourHostRespone) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetTourHostByCridentialsRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTourHostByCridentialsRequest) Reset()         { *m = GetTourHostByCridentialsRequest{} }
func (m *GetTourHostByCridentialsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTourHostByCridentialsRequest) ProtoMessage()    {}
func (*GetTourHostByCridentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{5}
}

func (m *GetTourHostByCridentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTourHostByCridentialsRequest.Unmarshal(m, b)
}
func (m *GetTourHostByCridentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTourHostByCridentialsRequest.Marshal(b, m, deterministic)
}
func (m *GetTourHostByCridentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTourHostByCridentialsRequest.Merge(m, src)
}
func (m *GetTourHostByCridentialsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTourHostByCridentialsRequest.Size(m)
}
func (m *GetTourHostByCridentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTourHostByCridentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTourHostByCridentialsRequest proto.InternalMessageInfo

func (m *GetTourHostByCridentialsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetTourHostByCridentialsRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetTourHostByCridentialsRespone struct {
	Data                 *TourHost `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTourHostByCridentialsRespone) Reset()         { *m = GetTourHostByCridentialsRespone{} }
func (m *GetTourHostByCridentialsRespone) String() string { return proto.CompactTextString(m) }
func (*GetTourHostByCridentialsRespone) ProtoMessage()    {}
func (*GetTourHostByCridentialsRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{6}
}

func (m *GetTourHostByCridentialsRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTourHostByCridentialsRespone.Unmarshal(m, b)
}
func (m *GetTourHostByCridentialsRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTourHostByCridentialsRespone.Marshal(b, m, deterministic)
}
func (m *GetTourHostByCridentialsRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTourHostByCridentialsRespone.Merge(m, src)
}
func (m *GetTourHostByCridentialsRespone) XXX_Size() int {
	return xxx_messageInfo_GetTourHostByCridentialsRespone.Size(m)
}
func (m *GetTourHostByCridentialsRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTourHostByCridentialsRespone.DiscardUnknown(m)
}

var xxx_messageInfo_GetTourHostByCridentialsRespone proto.InternalMessageInfo

func (m *GetTourHostByCridentialsRespone) GetData() *TourHost {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetTourHostRequest struct {
	HostId               string   `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTourHostRequest) Reset()         { *m = GetTourHostRequest{} }
func (m *GetTourHostRequest) String() string { return proto.CompactTextString(m) }
func (*GetTourHostRequest) ProtoMessage()    {}
func (*GetTourHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{7}
}

func (m *GetTourHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTourHostRequest.Unmarshal(m, b)
}
func (m *GetTourHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTourHostRequest.Marshal(b, m, deterministic)
}
func (m *GetTourHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTourHostRequest.Merge(m, src)
}
func (m *GetTourHostRequest) XXX_Size() int {
	return xxx_messageInfo_GetTourHostRequest.Size(m)
}
func (m *GetTourHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTourHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTourHostRequest proto.InternalMessageInfo

func (m *GetTourHostRequest) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

type GetTourHostRespone struct {
	Data                 *TourHost `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTourHostRespone) Reset()         { *m = GetTourHostRespone{} }
func (m *GetTourHostRespone) String() string { return proto.CompactTextString(m) }
func (*GetTourHostRespone) ProtoMessage()    {}
func (*GetTourHostRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{8}
}

func (m *GetTourHostRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTourHostRespone.Unmarshal(m, b)
}
func (m *GetTourHostRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTourHostRespone.Marshal(b, m, deterministic)
}
func (m *GetTourHostRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTourHostRespone.Merge(m, src)
}
func (m *GetTourHostRespone) XXX_Size() int {
	return xxx_messageInfo_GetTourHostRespone.Size(m)
}
func (m *GetTourHostRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTourHostRespone.DiscardUnknown(m)
}

var xxx_messageInfo_GetTourHostRespone proto.InternalMessageInfo

func (m *GetTourHostRespone) GetData() *TourHost {
	if m != nil {
		return m.Data
	}
	return nil
}

type HostCardID struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CardId               string               `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	PersonWithId         string               `protobuf:"bytes,3,opt,name=person_with_id,json=personWithId,proto3" json:"person_with_id,omitempty"`
	CardIdStatus         VerifiedStatus       `protobuf:"varint,4,opt,name=card_id_status,json=cardIdStatus,proto3,enum=host.VerifiedStatus" json:"card_id_status,omitempty"`
	VerifiedAt           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HostCardID) Reset()         { *m = HostCardID{} }
func (m *HostCardID) String() string { return proto.CompactTextString(m) }
func (*HostCardID) ProtoMessage()    {}
func (*HostCardID) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{9}
}

func (m *HostCardID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostCardID.Unmarshal(m, b)
}
func (m *HostCardID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostCardID.Marshal(b, m, deterministic)
}
func (m *HostCardID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostCardID.Merge(m, src)
}
func (m *HostCardID) XXX_Size() int {
	return xxx_messageInfo_HostCardID.Size(m)
}
func (m *HostCardID) XXX_DiscardUnknown() {
	xxx_messageInfo_HostCardID.DiscardUnknown(m)
}

var xxx_messageInfo_HostCardID proto.InternalMessageInfo

func (m *HostCardID) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *HostCardID) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

func (m *HostCardID) GetPersonWithId() string {
	if m != nil {
		return m.PersonWithId
	}
	return ""
}

func (m *HostCardID) GetCardIdStatus() VerifiedStatus {
	if m != nil {
		return m.CardIdStatus
	}
	return VerifiedStatus_PENDING
}

func (m *HostCardID) GetVerifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.VerifiedAt
	}
	return nil
}

type HostBussinessID struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	BussinessId          string               `protobuf:"bytes,2,opt,name=bussiness_id,json=bussinessId,proto3" json:"bussiness_id,omitempty"`
	BussinessIdStatus    VerifiedStatus       `protobuf:"varint,3,opt,name=bussiness_id_status,json=bussinessIdStatus,proto3,enum=host.VerifiedStatus" json:"bussiness_id_status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HostBussinessID) Reset()         { *m = HostBussinessID{} }
func (m *HostBussinessID) String() string { return proto.CompactTextString(m) }
func (*HostBussinessID) ProtoMessage()    {}
func (*HostBussinessID) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{10}
}

func (m *HostBussinessID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostBussinessID.Unmarshal(m, b)
}
func (m *HostBussinessID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostBussinessID.Marshal(b, m, deterministic)
}
func (m *HostBussinessID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostBussinessID.Merge(m, src)
}
func (m *HostBussinessID) XXX_Size() int {
	return xxx_messageInfo_HostBussinessID.Size(m)
}
func (m *HostBussinessID) XXX_DiscardUnknown() {
	xxx_messageInfo_HostBussinessID.DiscardUnknown(m)
}

var xxx_messageInfo_HostBussinessID proto.InternalMessageInfo

func (m *HostBussinessID) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *HostBussinessID) GetBussinessId() string {
	if m != nil {
		return m.BussinessId
	}
	return ""
}

func (m *HostBussinessID) GetBussinessIdStatus() VerifiedStatus {
	if m != nil {
		return m.BussinessIdStatus
	}
	return VerifiedStatus_PENDING
}

func (m *HostBussinessID) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMessage) Reset()         { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()    {}
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d66b36cac05c6a8, []int{11}
}

func (m *ResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMessage.Unmarshal(m, b)
}
func (m *ResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMessage.Marshal(b, m, deterministic)
}
func (m *ResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMessage.Merge(m, src)
}
func (m *ResponseMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseMessage.Size(m)
}
func (m *ResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMessage proto.InternalMessageInfo

func (m *ResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ResponseMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("host.VerifiedStatus", VerifiedStatus_name, VerifiedStatus_value)
	proto.RegisterType((*TourHost)(nil), "host.TourHost")
	proto.RegisterType((*UpdateTourHostRequest)(nil), "host.UpdateTourHostRequest")
	proto.RegisterType((*UpdateTourHostRespone)(nil), "host.UpdateTourHostRespone")
	proto.RegisterType((*CreateTourHostRequest)(nil), "host.CreateTourHostRequest")
	proto.RegisterType((*CreateTourHostRespone)(nil), "host.CreateTourHostRespone")
	proto.RegisterType((*GetTourHostByCridentialsRequest)(nil), "host.GetTourHostByCridentialsRequest")
	proto.RegisterType((*GetTourHostByCridentialsRespone)(nil), "host.GetTourHostByCridentialsRespone")
	proto.RegisterType((*GetTourHostRequest)(nil), "host.GetTourHostRequest")
	proto.RegisterType((*GetTourHostRespone)(nil), "host.GetTourHostRespone")
	proto.RegisterType((*HostCardID)(nil), "host.HostCardID")
	proto.RegisterType((*HostBussinessID)(nil), "host.HostBussinessID")
	proto.RegisterType((*ResponseMessage)(nil), "host.ResponseMessage")
}

func init() { proto.RegisterFile("pb/host.proto", fileDescriptor_7d66b36cac05c6a8) }

var fileDescriptor_7d66b36cac05c6a8 = []byte{
	// 1113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcf, 0x6f, 0x1a, 0x47,
	0x14, 0x2e, 0x36, 0x06, 0xfc, 0xc0, 0x18, 0x8f, 0x7f, 0x6d, 0x70, 0x2a, 0x3b, 0xdb, 0xa6, 0xb1,
	0xf2, 0xc3, 0x28, 0xe4, 0xd0, 0x36, 0x95, 0x2a, 0x11, 0x8c, 0x5c, 0x2a, 0xd5, 0x89, 0xb0, 0x93,
	0x1c, 0x57, 0x03, 0x3b, 0x98, 0x91, 0x60, 0x87, 0xce, 0xcc, 0x3a, 0x42, 0x55, 0x7b, 0xe8, 0xb5,
	0xea, 0xa9, 0xff, 0x57, 0x2f, 0x3d, 0xf7, 0xd6, 0x43, 0xff, 0x8c, 0x6a, 0x7e, 0xe1, 0x05, 0x1b,
	0xec, 0x54, 0xca, 0x25, 0xf2, 0x8d, 0xf7, 0xbe, 0x6f, 0xdf, 0xbc, 0x6f, 0x66, 0xbe, 0xb7, 0x0b,
	0xac, 0x0c, 0xdb, 0x95, 0x1e, 0x13, 0xf2, 0x60, 0xc8, 0x99, 0x64, 0x28, 0xad, 0x7e, 0x97, 0xef,
	0x9e, 0x31, 0x76, 0xd6, 0x27, 0x15, 0x3c, 0xa4, 0x15, 0x1c, 0x45, 0x4c, 0x62, 0x49, 0x59, 0x24,
	0x0c, 0xa7, 0xbc, 0x6b, 0x51, 0x1d, 0xb5, 0xe3, 0x6e, 0x45, 0xd2, 0x01, 0x11, 0x12, 0x0f, 0x86,
	0x86, 0xe0, 0xff, 0x96, 0x81, 0xdc, 0x29, 0x8b, 0xf9, 0x77, 0x4c, 0x48, 0xb4, 0x0d, 0x59, 0x55,
	0x33, 0xa0, 0xa1, 0x97, 0xda, 0x4b, 0xed, 0x2f, 0xb7, 0x32, 0x2a, 0x6c, 0x86, 0xe8, 0x53, 0x80,
	0x2e, 0xe5, 0x42, 0x06, 0x11, 0x1e, 0x10, 0x6f, 0x41, 0x63, 0xcb, 0x3a, 0x73, 0x8c, 0x07, 0x04,
	0xed, 0xc0, 0x72, 0x1f, 0x3b, 0x74, 0x51, 0xa3, 0x39, 0x95, 0xd0, 0xe0, 0x16, 0x64, 0xce, 0x48,
	0x14, 0x12, 0xee, 0xa5, 0x4d, 0x4d, 0x13, 0xa1, 0x7b, 0x50, 0x18, 0xf6, 0x58, 0x44, 0x82, 0x28,
	0x1e, 0xb4, 0x09, 0xf7, 0x96, 0x34, 0x9a, 0xd7, 0xb9, 0x63, 0x9d, 0x42, 0xdf, 0xc2, 0x4a, 0x88,
	0x25, 0x09, 0x58, 0x37, 0x68, 0x53, 0x2e, 0x7b, 0x5e, 0x66, 0x2f, 0xb5, 0x9f, 0xaf, 0x96, 0x0f,
	0x8c, 0xaa, 0x03, 0xa7, 0xea, 0xe0, 0xd4, 0xa9, 0x6a, 0xe5, 0xd5, 0x03, 0x2f, 0xbb, 0x2f, 0x14,
	0x1d, 0x95, 0x21, 0x37, 0xc4, 0x42, 0xbc, 0x63, 0x3c, 0xf4, 0xb2, 0xa6, 0x2d, 0x17, 0xa3, 0xcf,
	0x60, 0xa5, 0x1d, 0x0b, 0x1a, 0x11, 0x21, 0x4c, 0xdf, 0x39, 0x4d, 0x28, 0xb8, 0xa4, 0xee, 0xfd,
	0x11, 0xac, 0x8d, 0x49, 0x1d, 0x2c, 0xc9, 0x19, 0xe3, 0x23, 0x6f, 0x59, 0x13, 0x4b, 0x0e, 0xa8,
	0xdb, 0x3c, 0xf2, 0x20, 0x8b, 0xc3, 0x90, 0x13, 0x21, 0x3c, 0xd0, 0x14, 0x17, 0xa2, 0xfb, 0x50,
	0x1c, 0x97, 0xc1, 0x6d, 0x16, 0x4b, 0x2f, 0xaf, 0x09, 0xe3, 0x0e, 0x6a, 0x2a, 0x89, 0x1e, 0xc0,
	0xea, 0x90, 0x70, 0xc1, 0x22, 0xdc, 0xa7, 0x61, 0x20, 0x47, 0x43, 0xe2, 0x15, 0x34, 0xaf, 0x78,
	0x91, 0x3e, 0x1d, 0x0d, 0x75, 0x5b, 0x09, 0xa2, 0xdd, 0xbf, 0x15, 0xd3, 0xd6, 0x05, 0x60, 0x37,
	0xf1, 0x11, 0xac, 0x9d, 0x13, 0x4e, 0xbb, 0xb4, 0xa3, 0x6f, 0x86, 0xa9, 0x5b, 0x34, 0xe4, 0x24,
	0xa0, 0x2b, 0x57, 0x60, 0x7d, 0x82, 0x6c, 0x6b, 0xaf, 0x6a, 0x3a, 0x4a, 0x42, 0xb6, 0xfa, 0x2e,
	0xe4, 0xa9, 0x08, 0x0c, 0x40, 0x42, 0xaf, 0xb4, 0x97, 0xda, 0xcf, 0xb5, 0x80, 0x8a, 0x37, 0x36,
	0xa3, 0xb4, 0xe3, 0x4e, 0x87, 0xc5, 0x91, 0x74, 0xc5, 0xd6, 0x8c, 0x76, 0x9b, 0xb5, 0x75, 0x3c,
	0xc8, 0xb6, 0x71, 0x1f, 0x47, 0x1d, 0xe2, 0x21, 0xb3, 0x79, 0x36, 0x44, 0x77, 0x20, 0x17, 0x0b,
	0xc2, 0x83, 0x98, 0x86, 0xde, 0xba, 0x81, 0x54, 0xfc, 0x9a, 0x86, 0xe8, 0x6b, 0x80, 0x0e, 0x27,
	0x58, 0x92, 0x30, 0xc0, 0xd2, 0xdb, 0xb8, 0xf6, 0x72, 0x2c, 0x5b, 0x76, 0x4d, 0xa2, 0x0d, 0x58,
	0x22, 0x03, 0x4c, 0xfb, 0xde, 0xa6, 0x2e, 0x69, 0x02, 0xff, 0xdf, 0x0c, 0x6c, 0xbe, 0x1e, 0xaa,
	0x2b, 0xe4, 0x3c, 0xd1, 0x22, 0x3f, 0xc6, 0xe4, 0x43, 0x59, 0x63, 0xda, 0x02, 0xe9, 0x1b, 0x58,
	0x60, 0xe9, 0xff, 0x5b, 0x20, 0x33, 0x65, 0x81, 0x67, 0xb0, 0xe9, 0x7e, 0x07, 0x1d, 0x16, 0x75,
	0x29, 0x1f, 0xe8, 0xa3, 0xb5, 0x5e, 0xd9, 0x70, 0x60, 0x3d, 0x81, 0xdd, 0xfa, 0xe6, 0xe3, 0xf0,
	0x4d, 0xac, 0x6f, 0xf9, 0x4d, 0x7d, 0x63, 0xd9, 0xb3, 0x7c, 0x93, 0x98, 0xf1, 0x5b, 0x13, 0x33,
	0xfe, 0x0e, 0xe4, 0xda, 0xa3, 0x00, 0x87, 0x03, 0x1a, 0x79, 0xdb, 0x5a, 0x62, 0xb6, 0x3d, 0xaa,
	0xa9, 0xd0, 0xe7, 0x97, 0x9d, 0x26, 0x86, 0x2c, 0x52, 0x5b, 0x99, 0x0e, 0xb1, 0xc4, 0xda, 0x66,
	0xf9, 0xea, 0xce, 0x81, 0x7e, 0xe3, 0x5d, 0x69, 0xca, 0x96, 0x26, 0x22, 0x04, 0xe9, 0x0e, 0x0b,
	0x9d, 0xf7, 0xf4, 0x6f, 0xd5, 0xa6, 0xa4, 0xb2, 0xef, 0x2c, 0x67, 0x02, 0x6d, 0xef, 0xba, 0x1e,
	0x01, 0xb7, 0xf6, 0xbe, 0xb5, 0xf7, 0xad, 0xbd, 0x3f, 0xac, 0xbd, 0xa7, 0x9d, 0x36, 0xc7, 0xde,
	0x57, 0x9a, 0xf2, 0xbd, 0xed, 0x7d, 0x02, 0xbb, 0x47, 0x44, 0xba, 0x2a, 0x2f, 0x46, 0x75, 0x4e,
	0x43, 0x12, 0x49, 0x8a, 0xfb, 0xc2, 0xf9, 0x7c, 0xac, 0x2f, 0x95, 0xd4, 0x97, 0x74, 0xd1, 0xc2,
	0xa4, 0x8b, 0xfc, 0xc6, 0xbc, 0xa2, 0x46, 0x92, 0x3f, 0x21, 0xa9, 0x68, 0x24, 0x8d, 0xc5, 0x68,
	0xcc, 0x7f, 0x02, 0x28, 0x51, 0xe6, 0xba, 0xb1, 0xe3, 0x7f, 0x35, 0x45, 0xbf, 0xf9, 0x42, 0x7f,
	0xa7, 0x00, 0x54, 0x58, 0xc7, 0x3c, 0x6c, 0x1e, 0xce, 0x1e, 0x6c, 0xdb, 0x90, 0xed, 0x60, 0x1e,
	0x2a, 0xc0, 0x48, 0xce, 0xa8, 0xb0, 0x19, 0xa2, 0xcf, 0xc1, 0xfa, 0x2a, 0x78, 0x47, 0x65, 0x4f,
	0xe1, 0x66, 0x93, 0x0b, 0x26, 0xfb, 0x96, 0xca, 0x5e, 0x33, 0x44, 0xcf, 0xa1, 0x68, 0x1f, 0x0f,
	0x84, 0xc4, 0x32, 0x16, 0x7a, 0xba, 0x15, 0xab, 0x1b, 0xa6, 0x29, 0x77, 0xcf, 0x4f, 0x34, 0xd6,
	0x2a, 0x98, 0xda, 0x26, 0x42, 0xdf, 0x40, 0xde, 0x39, 0x43, 0x5d, 0xd0, 0xeb, 0x47, 0x1e, 0x38,
	0x7a, 0x4d, 0xfa, 0x7f, 0xa6, 0x60, 0x55, 0x9f, 0x44, 0x2c, 0xcc, 0x90, 0x98, 0x27, 0xf2, 0x1e,
	0xa8, 0xc1, 0x65, 0x47, 0xcc, 0x58, 0x69, 0x7e, 0x9c, 0x6b, 0x86, 0xe8, 0x10, 0xd6, 0x93, 0x14,
	0xa7, 0x66, 0x71, 0x8e, 0x9a, 0xb5, 0xc4, 0xf3, 0x56, 0xd2, 0xe4, 0x97, 0x68, 0xfa, 0x3d, 0xbe,
	0x44, 0xfd, 0x3a, 0xac, 0x9a, 0xf3, 0x15, 0xe4, 0x07, 0x22, 0x04, 0x3e, 0xd3, 0x7f, 0x99, 0x6c,
	0x1b, 0x56, 0x8e, 0x89, 0xd4, 0x34, 0x18, 0x18, 0x8a, 0x55, 0xe2, 0xc2, 0x87, 0x47, 0x50, 0x9c,
	0x6c, 0x12, 0xe5, 0x21, 0xfb, 0xaa, 0x71, 0x7c, 0xd8, 0x3c, 0x3e, 0x2a, 0x7d, 0x82, 0x0a, 0x90,
	0x7b, 0x79, 0xdc, 0x6a, 0xbc, 0x69, 0x36, 0xde, 0x96, 0x52, 0x2a, 0xaa, 0xd5, 0xeb, 0x8d, 0x57,
	0xa7, 0x8d, 0xc3, 0xd2, 0x82, 0x8a, 0x5a, 0x8d, 0xef, 0x1b, 0x75, 0x15, 0x2d, 0x56, 0x7f, 0x5f,
	0x82, 0x55, 0x77, 0xa3, 0x4e, 0x08, 0x3f, 0xa7, 0x1d, 0x82, 0x38, 0x14, 0x27, 0xdf, 0xbf, 0x68,
	0xde, 0x5b, 0xb9, 0x3c, 0x03, 0xd4, 0x57, 0xd8, 0xff, 0xe2, 0xd7, 0xbf, 0xfe, 0xf9, 0x63, 0x61,
	0xaf, 0xba, 0xa3, 0xff, 0xb0, 0x9e, 0x3f, 0xad, 0x48, 0x16, 0x73, 0xc5, 0x17, 0x95, 0x9f, 0xec,
	0x19, 0xfe, 0xfc, 0x3c, 0xf5, 0x10, 0xf5, 0xa0, 0x38, 0x39, 0x14, 0xd0, 0xbc, 0x51, 0x51, 0x9e,
	0x01, 0x9a, 0x35, 0xef, 0xea, 0x35, 0xb7, 0xfc, 0xb5, 0x4b, 0x6b, 0x9a, 0x95, 0xbc, 0x59, 0x06,
	0x47, 0xf7, 0x4d, 0xd9, 0x6b, 0xa6, 0x4a, 0xf9, 0x5a, 0x9a, 0xb1, 0x6f, 0x0d, 0xf2, 0x09, 0x0a,
	0xf2, 0x2e, 0x3d, 0xe5, 0xea, 0x5d, 0x85, 0x98, 0x12, 0x0c, 0x4a, 0x66, 0x5f, 0x13, 0x16, 0x2f,
	0x19, 0xf6, 0x45, 0xa6, 0xbc, 0x69, 0x32, 0x53, 0xd7, 0xca, 0xaf, 0xea, 0x7d, 0x78, 0x5c, 0x7d,
	0x70, 0x79, 0xef, 0xb5, 0xc1, 0x46, 0x4f, 0x94, 0x4d, 0x27, 0xcf, 0xe1, 0x17, 0xf7, 0x99, 0x36,
	0xed, 0xb9, 0xcd, 0x8b, 0x55, 0x13, 0xe9, 0x59, 0x4b, 0x7f, 0xa9, 0x97, 0x7e, 0x5a, 0x7d, 0x3c,
	0x73, 0xe9, 0xb1, 0xa7, 0x26, 0xd6, 0x6f, 0x67, 0xb4, 0x79, 0x9e, 0xfd, 0x17, 0x00, 0x00, 0xff,
	0xff, 0xc6, 0xb0, 0x48, 0xa1, 0xfc, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TourHostServiceClient is the client API for TourHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TourHostServiceClient interface {
	UpdateTourHost(ctx context.Context, in *UpdateTourHostRequest, opts ...grpc.CallOption) (*UpdateTourHostRespone, error)
	CreateTourHost(ctx context.Context, in *CreateTourHostRequest, opts ...grpc.CallOption) (*CreateTourHostRespone, error)
	GetTourHostByCridentials(ctx context.Context, in *GetTourHostByCridentialsRequest, opts ...grpc.CallOption) (*GetTourHostByCridentialsRespone, error)
	GetTourHost(ctx context.Context, in *GetTourHostRequest, opts ...grpc.CallOption) (*GetTourHostRespone, error)
	UpdateHostCardID(ctx context.Context, in *HostCardID, opts ...grpc.CallOption) (*ResponseMessage, error)
	UpdateHostBussinessID(ctx context.Context, in *HostBussinessID, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type tourHostServiceClient struct {
	cc *grpc.ClientConn
}

func NewTourHostServiceClient(cc *grpc.ClientConn) TourHostServiceClient {
	return &tourHostServiceClient{cc}
}

func (c *tourHostServiceClient) UpdateTourHost(ctx context.Context, in *UpdateTourHostRequest, opts ...grpc.CallOption) (*UpdateTourHostRespone, error) {
	out := new(UpdateTourHostRespone)
	err := c.cc.Invoke(ctx, "/host.TourHostService/UpdateTourHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) CreateTourHost(ctx context.Context, in *CreateTourHostRequest, opts ...grpc.CallOption) (*CreateTourHostRespone, error) {
	out := new(CreateTourHostRespone)
	err := c.cc.Invoke(ctx, "/host.TourHostService/CreateTourHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) GetTourHostByCridentials(ctx context.Context, in *GetTourHostByCridentialsRequest, opts ...grpc.CallOption) (*GetTourHostByCridentialsRespone, error) {
	out := new(GetTourHostByCridentialsRespone)
	err := c.cc.Invoke(ctx, "/host.TourHostService/GetTourHostByCridentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) GetTourHost(ctx context.Context, in *GetTourHostRequest, opts ...grpc.CallOption) (*GetTourHostRespone, error) {
	out := new(GetTourHostRespone)
	err := c.cc.Invoke(ctx, "/host.TourHostService/GetTourHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) UpdateHostCardID(ctx context.Context, in *HostCardID, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/host.TourHostService/UpdateHostCardID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) UpdateHostBussinessID(ctx context.Context, in *HostBussinessID, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/host.TourHostService/UpdateHostBussinessID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourHostServiceServer is the server API for TourHostService service.
type TourHostServiceServer interface {
	UpdateTourHost(context.Context, *UpdateTourHostRequest) (*UpdateTourHostRespone, error)
	CreateTourHost(context.Context, *CreateTourHostRequest) (*CreateTourHostRespone, error)
	GetTourHostByCridentials(context.Context, *GetTourHostByCridentialsRequest) (*GetTourHostByCridentialsRespone, error)
	GetTourHost(context.Context, *GetTourHostRequest) (*GetTourHostRespone, error)
	UpdateHostCardID(context.Context, *HostCardID) (*ResponseMessage, error)
	UpdateHostBussinessID(context.Context, *HostBussinessID) (*ResponseMessage, error)
}

// UnimplementedTourHostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTourHostServiceServer struct {
}

func (*UnimplementedTourHostServiceServer) UpdateTourHost(ctx context.Context, req *UpdateTourHostRequest) (*UpdateTourHostRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTourHost not implemented")
}
func (*UnimplementedTourHostServiceServer) CreateTourHost(ctx context.Context, req *CreateTourHostRequest) (*CreateTourHostRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTourHost not implemented")
}
func (*UnimplementedTourHostServiceServer) GetTourHostByCridentials(ctx context.Context, req *GetTourHostByCridentialsRequest) (*GetTourHostByCridentialsRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourHostByCridentials not implemented")
}
func (*UnimplementedTourHostServiceServer) GetTourHost(ctx context.Context, req *GetTourHostRequest) (*GetTourHostRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourHost not implemented")
}
func (*UnimplementedTourHostServiceServer) UpdateHostCardID(ctx context.Context, req *HostCardID) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHostCardID not implemented")
}
func (*UnimplementedTourHostServiceServer) UpdateHostBussinessID(ctx context.Context, req *HostBussinessID) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHostBussinessID not implemented")
}

func RegisterTourHostServiceServer(s *grpc.Server, srv TourHostServiceServer) {
	s.RegisterService(&_TourHostService_serviceDesc, srv)
}

func _TourHostService_UpdateTourHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTourHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).UpdateTourHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/host.TourHostService/UpdateTourHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).UpdateTourHost(ctx, req.(*UpdateTourHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_CreateTourHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).CreateTourHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/host.TourHostService/CreateTourHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).CreateTourHost(ctx, req.(*CreateTourHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_GetTourHostByCridentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourHostByCridentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).GetTourHostByCridentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/host.TourHostService/GetTourHostByCridentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).GetTourHostByCridentials(ctx, req.(*GetTourHostByCridentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_GetTourHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).GetTourHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/host.TourHostService/GetTourHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).GetTourHost(ctx, req.(*GetTourHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_UpdateHostCardID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostCardID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).UpdateHostCardID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/host.TourHostService/UpdateHostCardID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).UpdateHostCardID(ctx, req.(*HostCardID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_UpdateHostBussinessID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostBussinessID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).UpdateHostBussinessID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/host.TourHostService/UpdateHostBussinessID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).UpdateHostBussinessID(ctx, req.(*HostBussinessID))
	}
	return interceptor(ctx, in, info, handler)
}

var _TourHostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "host.TourHostService",
	HandlerType: (*TourHostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTourHost",
			Handler:    _TourHostService_UpdateTourHost_Handler,
		},
		{
			MethodName: "CreateTourHost",
			Handler:    _TourHostService_CreateTourHost_Handler,
		},
		{
			MethodName: "GetTourHostByCridentials",
			Handler:    _TourHostService_GetTourHostByCridentials_Handler,
		},
		{
			MethodName: "GetTourHost",
			Handler:    _TourHostService_GetTourHost_Handler,
		},
		{
			MethodName: "UpdateHostCardID",
			Handler:    _TourHostService_UpdateHostCardID_Handler,
		},
		{
			MethodName: "UpdateHostBussinessID",
			Handler:    _TourHostService_UpdateHostBussinessID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/host.proto",
}
