// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/tour-host-service.proto

package tourhostservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifiedStatus int32

const (
	VerifiedStatus_PENDING  VerifiedStatus = 0
	VerifiedStatus_ONREVIEW VerifiedStatus = 1
	VerifiedStatus_ACCEPTED VerifiedStatus = 2
	VerifiedStatus_REJECTED VerifiedStatus = 3
)

var VerifiedStatus_name = map[int32]string{
	0: "PENDING",
	1: "ONREVIEW",
	2: "ACCEPTED",
	3: "REJECTED",
}

var VerifiedStatus_value = map[string]int32{
	"PENDING":  0,
	"ONREVIEW": 1,
	"ACCEPTED": 2,
	"REJECTED": 3,
}

func (x VerifiedStatus) String() string {
	return proto.EnumName(VerifiedStatus_name, int32(x))
}

func (VerifiedStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{0}
}

type TourHost struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender               string               `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Password             string               `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	BusinessName         string               `protobuf:"bytes,8,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessCategory     string               `protobuf:"bytes,9,opt,name=business_category,json=businessCategory,proto3" json:"business_category,omitempty"`
	Address              string               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	BusinessAbout        string               `protobuf:"bytes,11,opt,name=business_about,json=businessAbout,proto3" json:"business_about,omitempty"`
	PersonalidType       string               `protobuf:"bytes,12,opt,name=personalid_type,json=personalidType,proto3" json:"personalid_type,omitempty"`
	PersonalidNumber     string               `protobuf:"bytes,13,opt,name=personalid_number,json=personalidNumber,proto3" json:"personalid_number,omitempty"`
	VerificationType     string               `protobuf:"bytes,14,opt,name=verification_type,json=verificationType,proto3" json:"verification_type,omitempty"`
	VerificationNumber   string               `protobuf:"bytes,15,opt,name=verification_number,json=verificationNumber,proto3" json:"verification_number,omitempty"`
	IsVerified           bool                 `protobuf:"varint,16,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	AccountNumber        string               `protobuf:"bytes,17,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance              string               `protobuf:"bytes,18,opt,name=balance,proto3" json:"balance,omitempty"`
	UserUid              string               `protobuf:"bytes,19,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Email                string               `protobuf:"bytes,21,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TourHost) Reset()         { *m = TourHost{} }
func (m *TourHost) String() string { return proto.CompactTextString(m) }
func (*TourHost) ProtoMessage()    {}
func (*TourHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{0}
}

func (m *TourHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TourHost.Unmarshal(m, b)
}
func (m *TourHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TourHost.Marshal(b, m, deterministic)
}
func (m *TourHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TourHost.Merge(m, src)
}
func (m *TourHost) XXX_Size() int {
	return xxx_messageInfo_TourHost.Size(m)
}
func (m *TourHost) XXX_DiscardUnknown() {
	xxx_messageInfo_TourHost.DiscardUnknown(m)
}

var xxx_messageInfo_TourHost proto.InternalMessageInfo

func (m *TourHost) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *TourHost) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *TourHost) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *TourHost) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *TourHost) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *TourHost) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *TourHost) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TourHost) GetBusinessName() string {
	if m != nil {
		return m.BusinessName
	}
	return ""
}

func (m *TourHost) GetBusinessCategory() string {
	if m != nil {
		return m.BusinessCategory
	}
	return ""
}

func (m *TourHost) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TourHost) GetBusinessAbout() string {
	if m != nil {
		return m.BusinessAbout
	}
	return ""
}

func (m *TourHost) GetPersonalidType() string {
	if m != nil {
		return m.PersonalidType
	}
	return ""
}

func (m *TourHost) GetPersonalidNumber() string {
	if m != nil {
		return m.PersonalidNumber
	}
	return ""
}

func (m *TourHost) GetVerificationType() string {
	if m != nil {
		return m.VerificationType
	}
	return ""
}

func (m *TourHost) GetVerificationNumber() string {
	if m != nil {
		return m.VerificationNumber
	}
	return ""
}

func (m *TourHost) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *TourHost) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *TourHost) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *TourHost) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *TourHost) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TourHost) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateTourHostRequest struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Dateofbirth          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=dateofbirth,proto3" json:"dateofbirth,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string               `protobuf:"bytes,7,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	BusinessName         string               `protobuf:"bytes,8,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessCategory     string               `protobuf:"bytes,9,opt,name=business_category,json=businessCategory,proto3" json:"business_category,omitempty"`
	Address              string               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	BusinessAbout        string               `protobuf:"bytes,11,opt,name=business_about,json=businessAbout,proto3" json:"business_about,omitempty"`
	PersonalidType       string               `protobuf:"bytes,12,opt,name=personalid_type,json=personalidType,proto3" json:"personalid_type,omitempty"`
	PersonalidNumber     string               `protobuf:"bytes,13,opt,name=personalid_number,json=personalidNumber,proto3" json:"personalid_number,omitempty"`
	VerificationType     string               `protobuf:"bytes,14,opt,name=verification_type,json=verificationType,proto3" json:"verification_type,omitempty"`
	VerificationNumber   string               `protobuf:"bytes,15,opt,name=verification_number,json=verificationNumber,proto3" json:"verification_number,omitempty"`
	IsVerified           bool                 `protobuf:"varint,16,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	AccountNumber        string               `protobuf:"bytes,17,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance              string               `protobuf:"bytes,18,opt,name=balance,proto3" json:"balance,omitempty"`
	UserUid              string               `protobuf:"bytes,19,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Email                string               `protobuf:"bytes,21,opt,name=email,proto3" json:"email,omitempty"`
	Gender               string               `protobuf:"bytes,22,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateTourHostRequest) Reset()         { *m = UpdateTourHostRequest{} }
func (m *UpdateTourHostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTourHostRequest) ProtoMessage()    {}
func (*UpdateTourHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{1}
}

func (m *UpdateTourHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTourHostRequest.Unmarshal(m, b)
}
func (m *UpdateTourHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTourHostRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTourHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTourHostRequest.Merge(m, src)
}
func (m *UpdateTourHostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTourHostRequest.Size(m)
}
func (m *UpdateTourHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTourHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTourHostRequest proto.InternalMessageInfo

func (m *UpdateTourHostRequest) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *UpdateTourHostRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateTourHostRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateTourHostRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UpdateTourHostRequest) GetDateofbirth() *timestamp.Timestamp {
	if m != nil {
		return m.Dateofbirth
	}
	return nil
}

func (m *UpdateTourHostRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateTourHostRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *UpdateTourHostRequest) GetBusinessName() string {
	if m != nil {
		return m.BusinessName
	}
	return ""
}

func (m *UpdateTourHostRequest) GetBusinessCategory() string {
	if m != nil {
		return m.BusinessCategory
	}
	return ""
}

func (m *UpdateTourHostRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpdateTourHostRequest) GetBusinessAbout() string {
	if m != nil {
		return m.BusinessAbout
	}
	return ""
}

func (m *UpdateTourHostRequest) GetPersonalidType() string {
	if m != nil {
		return m.PersonalidType
	}
	return ""
}

func (m *UpdateTourHostRequest) GetPersonalidNumber() string {
	if m != nil {
		return m.PersonalidNumber
	}
	return ""
}

func (m *UpdateTourHostRequest) GetVerificationType() string {
	if m != nil {
		return m.VerificationType
	}
	return ""
}

func (m *UpdateTourHostRequest) GetVerificationNumber() string {
	if m != nil {
		return m.VerificationNumber
	}
	return ""
}

func (m *UpdateTourHostRequest) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *UpdateTourHostRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *UpdateTourHostRequest) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *UpdateTourHostRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *UpdateTourHostRequest) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *UpdateTourHostRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateTourHostRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type UpdateTourHostResponse struct {
	Data                 *UpdateTourHostRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title                string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpdateTourHostResponse) Reset()         { *m = UpdateTourHostResponse{} }
func (m *UpdateTourHostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTourHostResponse) ProtoMessage()    {}
func (*UpdateTourHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{2}
}

func (m *UpdateTourHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTourHostResponse.Unmarshal(m, b)
}
func (m *UpdateTourHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTourHostResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTourHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTourHostResponse.Merge(m, src)
}
func (m *UpdateTourHostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTourHostResponse.Size(m)
}
func (m *UpdateTourHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTourHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTourHostResponse proto.InternalMessageInfo

func (m *UpdateTourHostResponse) GetData() *UpdateTourHostRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateTourHostResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UpdateTourHostResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type HostCardID struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CardId               string               `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	PersonWithId         string               `protobuf:"bytes,3,opt,name=person_with_id,json=personWithId,proto3" json:"person_with_id,omitempty"`
	CardIdStatus         VerifiedStatus       `protobuf:"varint,4,opt,name=card_id_status,json=cardIdStatus,proto3,enum=tourhostservice.VerifiedStatus" json:"card_id_status,omitempty"`
	VerifiedAt           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HostCardID) Reset()         { *m = HostCardID{} }
func (m *HostCardID) String() string { return proto.CompactTextString(m) }
func (*HostCardID) ProtoMessage()    {}
func (*HostCardID) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{3}
}

func (m *HostCardID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostCardID.Unmarshal(m, b)
}
func (m *HostCardID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostCardID.Marshal(b, m, deterministic)
}
func (m *HostCardID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostCardID.Merge(m, src)
}
func (m *HostCardID) XXX_Size() int {
	return xxx_messageInfo_HostCardID.Size(m)
}
func (m *HostCardID) XXX_DiscardUnknown() {
	xxx_messageInfo_HostCardID.DiscardUnknown(m)
}

var xxx_messageInfo_HostCardID proto.InternalMessageInfo

func (m *HostCardID) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *HostCardID) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

func (m *HostCardID) GetPersonWithId() string {
	if m != nil {
		return m.PersonWithId
	}
	return ""
}

func (m *HostCardID) GetCardIdStatus() VerifiedStatus {
	if m != nil {
		return m.CardIdStatus
	}
	return VerifiedStatus_PENDING
}

func (m *HostCardID) GetVerifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.VerifiedAt
	}
	return nil
}

type HostBussinessID struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	BussinessId          string               `protobuf:"bytes,2,opt,name=bussiness_id,json=bussinessId,proto3" json:"bussiness_id,omitempty"`
	BussinessIdStatus    VerifiedStatus       `protobuf:"varint,3,opt,name=bussiness_id_status,json=bussinessIdStatus,proto3,enum=tourhostservice.VerifiedStatus" json:"bussiness_id_status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HostBussinessID) Reset()         { *m = HostBussinessID{} }
func (m *HostBussinessID) String() string { return proto.CompactTextString(m) }
func (*HostBussinessID) ProtoMessage()    {}
func (*HostBussinessID) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{4}
}

func (m *HostBussinessID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostBussinessID.Unmarshal(m, b)
}
func (m *HostBussinessID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostBussinessID.Marshal(b, m, deterministic)
}
func (m *HostBussinessID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostBussinessID.Merge(m, src)
}
func (m *HostBussinessID) XXX_Size() int {
	return xxx_messageInfo_HostBussinessID.Size(m)
}
func (m *HostBussinessID) XXX_DiscardUnknown() {
	xxx_messageInfo_HostBussinessID.DiscardUnknown(m)
}

var xxx_messageInfo_HostBussinessID proto.InternalMessageInfo

func (m *HostBussinessID) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *HostBussinessID) GetBussinessId() string {
	if m != nil {
		return m.BussinessId
	}
	return ""
}

func (m *HostBussinessID) GetBussinessIdStatus() VerifiedStatus {
	if m != nil {
		return m.BussinessIdStatus
	}
	return VerifiedStatus_PENDING
}

func (m *HostBussinessID) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ResponseMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMessage) Reset()         { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()    {}
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{5}
}

func (m *ResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMessage.Unmarshal(m, b)
}
func (m *ResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMessage.Marshal(b, m, deterministic)
}
func (m *ResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMessage.Merge(m, src)
}
func (m *ResponseMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseMessage.Size(m)
}
func (m *ResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMessage proto.InternalMessageInfo

func (m *ResponseMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ResponseMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateTourHostRequest struct {
	HostId               string               `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Dateofbirth          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=dateofbirth,proto3" json:"dateofbirth,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string               `protobuf:"bytes,7,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	BusinessName         string               `protobuf:"bytes,8,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessCategory     string               `protobuf:"bytes,9,opt,name=business_category,json=businessCategory,proto3" json:"business_category,omitempty"`
	Address              string               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	BusinessAbout        string               `protobuf:"bytes,11,opt,name=business_about,json=businessAbout,proto3" json:"business_about,omitempty"`
	PersonalidType       string               `protobuf:"bytes,12,opt,name=personalid_type,json=personalidType,proto3" json:"personalid_type,omitempty"`
	PersonalidNumber     string               `protobuf:"bytes,13,opt,name=personalid_number,json=personalidNumber,proto3" json:"personalid_number,omitempty"`
	VerificationType     string               `protobuf:"bytes,14,opt,name=verification_type,json=verificationType,proto3" json:"verification_type,omitempty"`
	VerificationNumber   string               `protobuf:"bytes,15,opt,name=verification_number,json=verificationNumber,proto3" json:"verification_number,omitempty"`
	IsVerified           bool                 `protobuf:"varint,16,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	AccountNumber        string               `protobuf:"bytes,17,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance              string               `protobuf:"bytes,18,opt,name=balance,proto3" json:"balance,omitempty"`
	UserUid              string               `protobuf:"bytes,19,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Email                string               `protobuf:"bytes,21,opt,name=email,proto3" json:"email,omitempty"`
	Gender               string               `protobuf:"bytes,22,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTourHostRequest) Reset()         { *m = CreateTourHostRequest{} }
func (m *CreateTourHostRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTourHostRequest) ProtoMessage()    {}
func (*CreateTourHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{6}
}

func (m *CreateTourHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTourHostRequest.Unmarshal(m, b)
}
func (m *CreateTourHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTourHostRequest.Marshal(b, m, deterministic)
}
func (m *CreateTourHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTourHostRequest.Merge(m, src)
}
func (m *CreateTourHostRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTourHostRequest.Size(m)
}
func (m *CreateTourHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTourHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTourHostRequest proto.InternalMessageInfo

func (m *CreateTourHostRequest) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *CreateTourHostRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateTourHostRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateTourHostRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateTourHostRequest) GetDateofbirth() *timestamp.Timestamp {
	if m != nil {
		return m.Dateofbirth
	}
	return nil
}

func (m *CreateTourHostRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateTourHostRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *CreateTourHostRequest) GetBusinessName() string {
	if m != nil {
		return m.BusinessName
	}
	return ""
}

func (m *CreateTourHostRequest) GetBusinessCategory() string {
	if m != nil {
		return m.BusinessCategory
	}
	return ""
}

func (m *CreateTourHostRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateTourHostRequest) GetBusinessAbout() string {
	if m != nil {
		return m.BusinessAbout
	}
	return ""
}

func (m *CreateTourHostRequest) GetPersonalidType() string {
	if m != nil {
		return m.PersonalidType
	}
	return ""
}

func (m *CreateTourHostRequest) GetPersonalidNumber() string {
	if m != nil {
		return m.PersonalidNumber
	}
	return ""
}

func (m *CreateTourHostRequest) GetVerificationType() string {
	if m != nil {
		return m.VerificationType
	}
	return ""
}

func (m *CreateTourHostRequest) GetVerificationNumber() string {
	if m != nil {
		return m.VerificationNumber
	}
	return ""
}

func (m *CreateTourHostRequest) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *CreateTourHostRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *CreateTourHostRequest) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *CreateTourHostRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *CreateTourHostRequest) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *CreateTourHostRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateTourHostRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type CreateTourHostResponse struct {
	Data                 *CreateTourHostRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title                string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateTourHostResponse) Reset()         { *m = CreateTourHostResponse{} }
func (m *CreateTourHostResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTourHostResponse) ProtoMessage()    {}
func (*CreateTourHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{7}
}

func (m *CreateTourHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTourHostResponse.Unmarshal(m, b)
}
func (m *CreateTourHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTourHostResponse.Marshal(b, m, deterministic)
}
func (m *CreateTourHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTourHostResponse.Merge(m, src)
}
func (m *CreateTourHostResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTourHostResponse.Size(m)
}
func (m *CreateTourHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTourHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTourHostResponse proto.InternalMessageInfo

func (m *CreateTourHostResponse) GetData() *CreateTourHostRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateTourHostResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateTourHostResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetTourHostByCridentialsRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTourHostByCridentialsRequest) Reset()         { *m = GetTourHostByCridentialsRequest{} }
func (m *GetTourHostByCridentialsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTourHostByCridentialsRequest) ProtoMessage()    {}
func (*GetTourHostByCridentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{8}
}

func (m *GetTourHostByCridentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTourHostByCridentialsRequest.Unmarshal(m, b)
}
func (m *GetTourHostByCridentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTourHostByCridentialsRequest.Marshal(b, m, deterministic)
}
func (m *GetTourHostByCridentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTourHostByCridentialsRequest.Merge(m, src)
}
func (m *GetTourHostByCridentialsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTourHostByCridentialsRequest.Size(m)
}
func (m *GetTourHostByCridentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTourHostByCridentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTourHostByCridentialsRequest proto.InternalMessageInfo

func (m *GetTourHostByCridentialsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetTourHostByCridentialsRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetTourHostByCridentialsResponse struct {
	Data                 *TourHost `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTourHostByCridentialsResponse) Reset()         { *m = GetTourHostByCridentialsResponse{} }
func (m *GetTourHostByCridentialsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTourHostByCridentialsResponse) ProtoMessage()    {}
func (*GetTourHostByCridentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{9}
}

func (m *GetTourHostByCridentialsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTourHostByCridentialsResponse.Unmarshal(m, b)
}
func (m *GetTourHostByCridentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTourHostByCridentialsResponse.Marshal(b, m, deterministic)
}
func (m *GetTourHostByCridentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTourHostByCridentialsResponse.Merge(m, src)
}
func (m *GetTourHostByCridentialsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTourHostByCridentialsResponse.Size(m)
}
func (m *GetTourHostByCridentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTourHostByCridentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTourHostByCridentialsResponse proto.InternalMessageInfo

func (m *GetTourHostByCridentialsResponse) GetData() *TourHost {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetTourHostByIdResponse struct {
	Data                 *TourHost `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTourHostByIdResponse) Reset()         { *m = GetTourHostByIdResponse{} }
func (m *GetTourHostByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetTourHostByIdResponse) ProtoMessage()    {}
func (*GetTourHostByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{10}
}

func (m *GetTourHostByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTourHostByIdResponse.Unmarshal(m, b)
}
func (m *GetTourHostByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTourHostByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetTourHostByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTourHostByIdResponse.Merge(m, src)
}
func (m *GetTourHostByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetTourHostByIdResponse.Size(m)
}
func (m *GetTourHostByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTourHostByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTourHostByIdResponse proto.InternalMessageInfo

func (m *GetTourHostByIdResponse) GetData() *TourHost {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetTourHostRequest struct {
	HostId               string   `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTourHostRequest) Reset()         { *m = GetTourHostRequest{} }
func (m *GetTourHostRequest) String() string { return proto.CompactTextString(m) }
func (*GetTourHostRequest) ProtoMessage()    {}
func (*GetTourHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{11}
}

func (m *GetTourHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTourHostRequest.Unmarshal(m, b)
}
func (m *GetTourHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTourHostRequest.Marshal(b, m, deterministic)
}
func (m *GetTourHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTourHostRequest.Merge(m, src)
}
func (m *GetTourHostRequest) XXX_Size() int {
	return xxx_messageInfo_GetTourHostRequest.Size(m)
}
func (m *GetTourHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTourHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTourHostRequest proto.InternalMessageInfo

func (m *GetTourHostRequest) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

type GetTourHostRespone struct {
	Data                 *TourHost `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTourHostRespone) Reset()         { *m = GetTourHostRespone{} }
func (m *GetTourHostRespone) String() string { return proto.CompactTextString(m) }
func (*GetTourHostRespone) ProtoMessage()    {}
func (*GetTourHostRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebb9a286c58b861, []int{12}
}

func (m *GetTourHostRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTourHostRespone.Unmarshal(m, b)
}
func (m *GetTourHostRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTourHostRespone.Marshal(b, m, deterministic)
}
func (m *GetTourHostRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTourHostRespone.Merge(m, src)
}
func (m *GetTourHostRespone) XXX_Size() int {
	return xxx_messageInfo_GetTourHostRespone.Size(m)
}
func (m *GetTourHostRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTourHostRespone.DiscardUnknown(m)
}

var xxx_messageInfo_GetTourHostRespone proto.InternalMessageInfo

func (m *GetTourHostRespone) GetData() *TourHost {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("tourhostservice.VerifiedStatus", VerifiedStatus_name, VerifiedStatus_value)
	proto.RegisterType((*TourHost)(nil), "tourhostservice.TourHost")
	proto.RegisterType((*UpdateTourHostRequest)(nil), "tourhostservice.UpdateTourHostRequest")
	proto.RegisterType((*UpdateTourHostResponse)(nil), "tourhostservice.UpdateTourHostResponse")
	proto.RegisterType((*HostCardID)(nil), "tourhostservice.HostCardID")
	proto.RegisterType((*HostBussinessID)(nil), "tourhostservice.HostBussinessID")
	proto.RegisterType((*ResponseMessage)(nil), "tourhostservice.ResponseMessage")
	proto.RegisterType((*CreateTourHostRequest)(nil), "tourhostservice.CreateTourHostRequest")
	proto.RegisterType((*CreateTourHostResponse)(nil), "tourhostservice.CreateTourHostResponse")
	proto.RegisterType((*GetTourHostByCridentialsRequest)(nil), "tourhostservice.GetTourHostByCridentialsRequest")
	proto.RegisterType((*GetTourHostByCridentialsResponse)(nil), "tourhostservice.GetTourHostByCridentialsResponse")
	proto.RegisterType((*GetTourHostByIdResponse)(nil), "tourhostservice.GetTourHostByIdResponse")
	proto.RegisterType((*GetTourHostRequest)(nil), "tourhostservice.GetTourHostRequest")
	proto.RegisterType((*GetTourHostRespone)(nil), "tourhostservice.GetTourHostRespone")
}

func init() {
	proto.RegisterFile("pb/tour-host-service.proto", fileDescriptor_1ebb9a286c58b861)
}

var fileDescriptor_1ebb9a286c58b861 = []byte{
	// 1151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcd, 0x4f, 0x1b, 0x47,
	0x14, 0xef, 0x12, 0x62, 0x9b, 0x67, 0x63, 0x9b, 0xe1, 0x6b, 0x31, 0x89, 0x70, 0x36, 0x6d, 0x40,
	0x89, 0xb0, 0x1b, 0xe7, 0xd4, 0xb4, 0xaa, 0x04, 0xc6, 0x22, 0xae, 0x54, 0x48, 0x0d, 0x49, 0x8e,
	0xab, 0xb1, 0x77, 0x0c, 0x23, 0xd9, 0xbb, 0xdb, 0x9d, 0x59, 0x22, 0x14, 0xf5, 0x43, 0xbd, 0xb5,
	0x3d, 0xf6, 0xd6, 0xbf, 0xa8, 0x52, 0x8f, 0x3d, 0xf5, 0xde, 0x43, 0xff, 0x8c, 0x6a, 0xbe, 0xcc,
	0xda, 0xc6, 0x60, 0xfa, 0x71, 0xa9, 0xb8, 0xf9, 0xbd, 0xf7, 0xdb, 0x37, 0xef, 0x37, 0x33, 0xbf,
	0xdf, 0xae, 0xa1, 0x14, 0xb6, 0xab, 0x3c, 0x88, 0xa3, 0xed, 0xd3, 0x80, 0xf1, 0x6d, 0x46, 0xa2,
	0x33, 0xda, 0x21, 0x95, 0x30, 0x0a, 0x78, 0x80, 0x0a, 0xa2, 0x20, 0xf2, 0x3a, 0x5d, 0xba, 0x77,
	0x12, 0x04, 0x27, 0x3d, 0x52, 0xc5, 0x21, 0xad, 0x62, 0xdf, 0x0f, 0x38, 0xe6, 0x34, 0xf0, 0x99,
	0x82, 0x97, 0x36, 0x74, 0x55, 0x46, 0xed, 0xb8, 0x5b, 0xe5, 0xb4, 0x4f, 0x18, 0xc7, 0xfd, 0x50,
	0x01, 0x9c, 0x1f, 0x53, 0x90, 0x39, 0x0e, 0xe2, 0xe8, 0x45, 0xc0, 0x38, 0x5a, 0x85, 0xb4, 0x68,
	0xed, 0x52, 0xcf, 0xb6, 0xca, 0xd6, 0xd6, 0x5c, 0x2b, 0x25, 0xc2, 0xa6, 0x87, 0xee, 0x03, 0x74,
	0x69, 0xc4, 0xb8, 0xeb, 0xe3, 0x3e, 0xb1, 0x67, 0x64, 0x6d, 0x4e, 0x66, 0x0e, 0x70, 0x9f, 0xa0,
	0x75, 0x98, 0xeb, 0x61, 0x53, 0xbd, 0x23, 0xab, 0x19, 0x91, 0x90, 0xc5, 0x15, 0x48, 0x9d, 0x10,
	0xdf, 0x23, 0x91, 0x3d, 0xab, 0x7a, 0xaa, 0x08, 0x3d, 0x80, 0x5c, 0x78, 0x1a, 0xf8, 0xc4, 0xf5,
	0xe3, 0x7e, 0x9b, 0x44, 0xf6, 0x5d, 0x59, 0xcd, 0xca, 0xdc, 0x81, 0x4c, 0xa1, 0x4f, 0x61, 0xde,
	0xc3, 0x9c, 0xb8, 0x41, 0xd7, 0x6d, 0xd3, 0x88, 0x9f, 0xda, 0xa9, 0xb2, 0xb5, 0x95, 0xad, 0x95,
	0x2a, 0x8a, 0x55, 0xc5, 0xb0, 0xaa, 0x1c, 0x1b, 0x56, 0xad, 0xac, 0x78, 0xe0, 0xb0, 0xbb, 0x2b,
	0xe0, 0xa8, 0x04, 0x99, 0x10, 0x33, 0xf6, 0x36, 0x88, 0x3c, 0x3b, 0xad, 0xc6, 0x32, 0x31, 0x7a,
	0x08, 0xf3, 0xed, 0x98, 0x51, 0x9f, 0x30, 0xa6, 0xe6, 0xce, 0x48, 0x40, 0xce, 0x24, 0xe5, 0xec,
	0x4f, 0x60, 0x61, 0x00, 0xea, 0x60, 0x4e, 0x4e, 0x82, 0xe8, 0xdc, 0x9e, 0x93, 0xc0, 0xa2, 0x29,
	0xd4, 0x75, 0x1e, 0xd9, 0x90, 0xc6, 0x9e, 0x17, 0x11, 0xc6, 0x6c, 0x90, 0x10, 0x13, 0xa2, 0x0f,
	0x20, 0x3f, 0x68, 0x83, 0xdb, 0x41, 0xcc, 0xed, 0xac, 0x04, 0x0c, 0x26, 0xd8, 0x11, 0x49, 0xb4,
	0x09, 0x85, 0x90, 0x44, 0x2c, 0xf0, 0x71, 0x8f, 0x7a, 0x2e, 0x3f, 0x0f, 0x89, 0x9d, 0x93, 0xb8,
	0xfc, 0x45, 0xfa, 0xf8, 0x3c, 0x94, 0x63, 0x25, 0x80, 0x7a, 0xff, 0xe6, 0xd5, 0x58, 0x17, 0x05,
	0xbd, 0x89, 0x4f, 0x60, 0xe1, 0x8c, 0x44, 0xb4, 0x4b, 0x3b, 0xf2, 0x66, 0xa8, 0xbe, 0x79, 0x05,
	0x4e, 0x16, 0x64, 0xe7, 0x2a, 0x2c, 0x0e, 0x81, 0x75, 0xef, 0x82, 0x84, 0xa3, 0x64, 0x49, 0x77,
	0xdf, 0x80, 0x2c, 0x65, 0xae, 0x2a, 0x10, 0xcf, 0x2e, 0x96, 0xad, 0xad, 0x4c, 0x0b, 0x28, 0x7b,
	0xad, 0x33, 0x82, 0x3b, 0xee, 0x74, 0x82, 0xd8, 0xe7, 0xa6, 0xd9, 0x82, 0xe2, 0xae, 0xb3, 0xba,
	0x8f, 0x0d, 0xe9, 0x36, 0xee, 0x61, 0xbf, 0x43, 0x6c, 0xa4, 0x36, 0x4f, 0x87, 0x68, 0x0d, 0x32,
	0x31, 0x23, 0x91, 0x1b, 0x53, 0xcf, 0x5e, 0x54, 0x25, 0x11, 0xbf, 0xa2, 0x1e, 0xfa, 0x08, 0xa0,
	0x13, 0x11, 0xcc, 0x89, 0xe7, 0x62, 0x6e, 0x2f, 0x5d, 0x7b, 0x39, 0xe6, 0x34, 0x7a, 0x87, 0xa3,
	0x25, 0xb8, 0x4b, 0xfa, 0x98, 0xf6, 0xec, 0x65, 0xd9, 0x52, 0x05, 0xce, 0xaf, 0x29, 0x58, 0x7e,
	0x15, 0x8a, 0x2b, 0x64, 0x34, 0xd1, 0x22, 0x5f, 0xc6, 0xe4, 0xbf, 0x92, 0xc6, 0xa8, 0x04, 0x66,
	0xc7, 0x25, 0xf0, 0x09, 0xc8, 0x1b, 0x1d, 0x74, 0x95, 0x00, 0xee, 0x4e, 0x27, 0x00, 0x0d, 0x1f,
	0x12, 0x40, 0x6a, 0x44, 0x00, 0xcf, 0x60, 0xd9, 0xfc, 0x76, 0x3b, 0x81, 0xdf, 0xa5, 0x51, 0x5f,
	0x1e, 0xac, 0x56, 0xca, 0x92, 0x29, 0xd6, 0x13, 0xb5, 0x5b, 0xd5, 0xfc, 0x3f, 0x54, 0x13, 0xcb,
	0x3b, 0x3e, 0xad, 0x6a, 0x34, 0x7a, 0x92, 0x6a, 0x12, 0x0e, 0xbf, 0x92, 0x74, 0x78, 0xe7, 0x6b,
	0x58, 0x19, 0x15, 0x13, 0x0b, 0x03, 0x9f, 0x11, 0xf4, 0x1c, 0x66, 0x3d, 0xcc, 0xb1, 0x94, 0x52,
	0xb6, 0xf6, 0xa8, 0x32, 0xf2, 0x52, 0xab, 0x5c, 0xaa, 0xc1, 0x96, 0x7c, 0x06, 0x21, 0x98, 0xed,
	0x04, 0x9e, 0x91, 0x9a, 0xfc, 0x2d, 0xe6, 0xe2, 0x94, 0xf7, 0x8c, 0xc2, 0x54, 0xe0, 0xfc, 0x69,
	0x01, 0x88, 0xe7, 0xeb, 0x38, 0xf2, 0x9a, 0x7b, 0x93, 0x25, 0xbc, 0x0a, 0xe9, 0x0e, 0x8e, 0x3c,
	0x51, 0x50, 0x4d, 0x53, 0x22, 0x6c, 0x7a, 0xe8, 0x7d, 0xd0, 0x77, 0xc8, 0x7d, 0x4b, 0xf9, 0xa9,
	0xa8, 0xab, 0xfe, 0x39, 0x95, 0x7d, 0x43, 0xf9, 0x69, 0xd3, 0x43, 0x0d, 0xc8, 0xeb, 0xc7, 0x5d,
	0xc6, 0x31, 0x8f, 0x99, 0xd4, 0x71, 0xbe, 0xb6, 0x31, 0x46, 0xcb, 0x1c, 0xef, 0x91, 0x84, 0xb5,
	0x72, 0x6a, 0x19, 0x15, 0xa1, 0x8f, 0x21, 0x6b, 0x2e, 0x84, 0x38, 0x97, 0xeb, 0x95, 0x0e, 0x06,
	0xbe, 0xc3, 0x9d, 0xdf, 0x2d, 0x28, 0x08, 0xaa, 0xbb, 0x31, 0x53, 0xda, 0xb8, 0x8a, 0xef, 0x03,
	0x10, 0x7a, 0xd5, 0xca, 0x1a, 0x90, 0xce, 0x0e, 0x72, 0x4d, 0x0f, 0x1d, 0xc2, 0x62, 0x12, 0x62,
	0x88, 0xdd, 0x99, 0x8e, 0xd8, 0x42, 0xa2, 0x95, 0x66, 0x37, 0x6c, 0xd5, 0xb3, 0x37, 0xb0, 0x6a,
	0xa7, 0x0e, 0x05, 0x73, 0x71, 0x3e, 0x27, 0x8c, 0xe1, 0x13, 0xf9, 0x4d, 0xa1, 0x27, 0xd2, 0xcc,
	0x54, 0x24, 0xf4, 0xd0, 0x57, 0x10, 0x4d, 0xca, 0x84, 0xd2, 0xd9, 0xeb, 0xb2, 0xe5, 0xad, 0xb3,
	0xdf, 0x3a, 0xfb, 0xad, 0xb3, 0xff, 0x63, 0x67, 0x1f, 0x15, 0xd3, 0x94, 0xce, 0x7e, 0xa9, 0x06,
	0x6f, 0xec, 0xec, 0x47, 0xb0, 0xb1, 0x4f, 0xb8, 0xe9, 0xb2, 0x7b, 0x5e, 0x8f, 0xa8, 0x47, 0x7c,
	0x4e, 0x71, 0x8f, 0x19, 0x59, 0x0f, 0x08, 0x59, 0x49, 0x42, 0x49, 0xd9, 0xcc, 0x0c, 0xcb, 0xc6,
	0xf9, 0x02, 0xca, 0x93, 0x9b, 0x6a, 0x7a, 0xdb, 0x43, 0xf4, 0xd6, 0xc6, 0xe8, 0x0d, 0x88, 0x49,
	0x98, 0xf3, 0x02, 0x56, 0x87, 0x5a, 0x36, 0xbd, 0xbf, 0xdb, 0x69, 0x1b, 0x50, 0xa2, 0xd3, 0x75,
	0xde, 0xe5, 0xd4, 0x47, 0xe0, 0x62, 0xd1, 0x9b, 0xae, 0xf9, 0x78, 0x1f, 0xf2, 0xc3, 0xc6, 0x8e,
	0xb2, 0x90, 0x7e, 0xd9, 0x38, 0xd8, 0x6b, 0x1e, 0xec, 0x17, 0xdf, 0x43, 0x39, 0xc8, 0x1c, 0x1e,
	0xb4, 0x1a, 0xaf, 0x9b, 0x8d, 0x37, 0x45, 0x4b, 0x44, 0x3b, 0xf5, 0x7a, 0xe3, 0xe5, 0x71, 0x63,
	0xaf, 0x38, 0x23, 0xa2, 0x56, 0xe3, 0xb3, 0x46, 0x5d, 0x44, 0x77, 0x6a, 0xbf, 0xa4, 0xa0, 0x60,
	0x7a, 0x1f, 0xa9, 0xb5, 0xd0, 0xf7, 0x16, 0xe4, 0x87, 0x5f, 0xf3, 0x68, 0xca, 0xef, 0x80, 0xd2,
	0xe6, 0xb5, 0x38, 0xb5, 0xc7, 0xce, 0xa3, 0xef, 0x7e, 0xfb, 0xe3, 0xa7, 0x99, 0x72, 0x6d, 0x5d,
	0xfe, 0x3b, 0x3e, 0x7b, 0x5a, 0x1d, 0x3c, 0x57, 0x7d, 0xa7, 0xf7, 0xed, 0xab, 0xe7, 0xd6, 0x63,
	0xf4, 0x0e, 0x0a, 0x23, 0xc7, 0x84, 0x26, 0x6f, 0x4e, 0x69, 0x6b, 0xac, 0x34, 0xe1, 0x8c, 0x9d,
	0x87, 0x72, 0xfd, 0xfb, 0xe8, 0xaa, 0xf5, 0xd1, 0xb7, 0x16, 0x14, 0xd5, 0xfc, 0x89, 0x6f, 0x95,
	0xf5, 0xb1, 0x35, 0x2e, 0x8a, 0xa5, 0xf2, 0x58, 0x71, 0xe4, 0xfd, 0xe8, 0x6c, 0xcb, 0x85, 0x37,
	0x6b, 0xce, 0xf8, 0xc2, 0xd2, 0x9a, 0xce, 0x87, 0xf9, 0xff, 0x60, 0x99, 0xbf, 0x3d, 0xa3, 0xdf,
	0x10, 0xe5, 0x4b, 0xe7, 0x48, 0x20, 0xfe, 0xfd, 0x61, 0xbe, 0x81, 0xfc, 0xb0, 0x49, 0xa0, 0x29,
	0x5d, 0xe4, 0x92, 0x7b, 0x71, 0xb9, 0x49, 0x39, 0xf7, 0xe4, 0x44, 0x2b, 0xce, 0xc2, 0xd8, 0x44,
	0x62, 0x80, 0x9f, 0x2d, 0xb0, 0x27, 0x19, 0x01, 0xfa, 0xf0, 0xea, 0xc3, 0x1f, 0x37, 0xa2, 0xd2,
	0xd3, 0x1b, 0x3c, 0xa1, 0xe7, 0x5b, 0x93, 0xf3, 0x2d, 0xa2, 0xf1, 0xf9, 0xda, 0x29, 0x69, 0xe3,
	0xcf, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x28, 0x32, 0x99, 0x9f, 0x24, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TourHostServiceClient is the client API for TourHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TourHostServiceClient interface {
	UpdateTourHost(ctx context.Context, in *UpdateTourHostRequest, opts ...grpc.CallOption) (*UpdateTourHostResponse, error)
	GetTourHostById(ctx context.Context, in *TourHost, opts ...grpc.CallOption) (*GetTourHostByIdResponse, error)
	UpdateHostCardID(ctx context.Context, in *HostCardID, opts ...grpc.CallOption) (*ResponseMessage, error)
	UpdateHostBussinessID(ctx context.Context, in *HostBussinessID, opts ...grpc.CallOption) (*ResponseMessage, error)
	CreateTourHost(ctx context.Context, in *CreateTourHostRequest, opts ...grpc.CallOption) (*CreateTourHostResponse, error)
	//    rpc GetTourHostByCridentials(GetTourHostByCridentialsRequest) returns (GetTourHostByCridentialsResponse);
	GetTourHostByCridentials(ctx context.Context, in *GetTourHostByCridentialsRequest, opts ...grpc.CallOption) (*GetTourHostByCridentialsResponse, error)
}

type tourHostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourHostServiceClient(cc grpc.ClientConnInterface) TourHostServiceClient {
	return &tourHostServiceClient{cc}
}

func (c *tourHostServiceClient) UpdateTourHost(ctx context.Context, in *UpdateTourHostRequest, opts ...grpc.CallOption) (*UpdateTourHostResponse, error) {
	out := new(UpdateTourHostResponse)
	err := c.cc.Invoke(ctx, "/tourhostservice.TourHostService/UpdateTourHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) GetTourHostById(ctx context.Context, in *TourHost, opts ...grpc.CallOption) (*GetTourHostByIdResponse, error) {
	out := new(GetTourHostByIdResponse)
	err := c.cc.Invoke(ctx, "/tourhostservice.TourHostService/GetTourHostById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) UpdateHostCardID(ctx context.Context, in *HostCardID, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/tourhostservice.TourHostService/UpdateHostCardID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) UpdateHostBussinessID(ctx context.Context, in *HostBussinessID, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/tourhostservice.TourHostService/UpdateHostBussinessID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) CreateTourHost(ctx context.Context, in *CreateTourHostRequest, opts ...grpc.CallOption) (*CreateTourHostResponse, error) {
	out := new(CreateTourHostResponse)
	err := c.cc.Invoke(ctx, "/tourhostservice.TourHostService/CreateTourHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourHostServiceClient) GetTourHostByCridentials(ctx context.Context, in *GetTourHostByCridentialsRequest, opts ...grpc.CallOption) (*GetTourHostByCridentialsResponse, error) {
	out := new(GetTourHostByCridentialsResponse)
	err := c.cc.Invoke(ctx, "/tourhostservice.TourHostService/GetTourHostByCridentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourHostServiceServer is the server API for TourHostService service.
type TourHostServiceServer interface {
	UpdateTourHost(context.Context, *UpdateTourHostRequest) (*UpdateTourHostResponse, error)
	GetTourHostById(context.Context, *TourHost) (*GetTourHostByIdResponse, error)
	UpdateHostCardID(context.Context, *HostCardID) (*ResponseMessage, error)
	UpdateHostBussinessID(context.Context, *HostBussinessID) (*ResponseMessage, error)
	CreateTourHost(context.Context, *CreateTourHostRequest) (*CreateTourHostResponse, error)
	//    rpc GetTourHostByCridentials(GetTourHostByCridentialsRequest) returns (GetTourHostByCridentialsResponse);
	GetTourHostByCridentials(context.Context, *GetTourHostByCridentialsRequest) (*GetTourHostByCridentialsResponse, error)
}

// UnimplementedTourHostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTourHostServiceServer struct {
}

func (*UnimplementedTourHostServiceServer) UpdateTourHost(ctx context.Context, req *UpdateTourHostRequest) (*UpdateTourHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTourHost not implemented")
}
func (*UnimplementedTourHostServiceServer) GetTourHostById(ctx context.Context, req *TourHost) (*GetTourHostByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourHostById not implemented")
}
func (*UnimplementedTourHostServiceServer) UpdateHostCardID(ctx context.Context, req *HostCardID) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHostCardID not implemented")
}
func (*UnimplementedTourHostServiceServer) UpdateHostBussinessID(ctx context.Context, req *HostBussinessID) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHostBussinessID not implemented")
}
func (*UnimplementedTourHostServiceServer) CreateTourHost(ctx context.Context, req *CreateTourHostRequest) (*CreateTourHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTourHost not implemented")
}
func (*UnimplementedTourHostServiceServer) GetTourHostByCridentials(ctx context.Context, req *GetTourHostByCridentialsRequest) (*GetTourHostByCridentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourHostByCridentials not implemented")
}

func RegisterTourHostServiceServer(s *grpc.Server, srv TourHostServiceServer) {
	s.RegisterService(&_TourHostService_serviceDesc, srv)
}

func _TourHostService_UpdateTourHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTourHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).UpdateTourHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tourhostservice.TourHostService/UpdateTourHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).UpdateTourHost(ctx, req.(*UpdateTourHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_GetTourHostById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourHost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).GetTourHostById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tourhostservice.TourHostService/GetTourHostById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).GetTourHostById(ctx, req.(*TourHost))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_UpdateHostCardID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostCardID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).UpdateHostCardID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tourhostservice.TourHostService/UpdateHostCardID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).UpdateHostCardID(ctx, req.(*HostCardID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_UpdateHostBussinessID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostBussinessID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).UpdateHostBussinessID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tourhostservice.TourHostService/UpdateHostBussinessID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).UpdateHostBussinessID(ctx, req.(*HostBussinessID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_CreateTourHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).CreateTourHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tourhostservice.TourHostService/CreateTourHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).CreateTourHost(ctx, req.(*CreateTourHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourHostService_GetTourHostByCridentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourHostByCridentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourHostServiceServer).GetTourHostByCridentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tourhostservice.TourHostService/GetTourHostByCridentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourHostServiceServer).GetTourHostByCridentials(ctx, req.(*GetTourHostByCridentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TourHostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tourhostservice.TourHostService",
	HandlerType: (*TourHostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTourHost",
			Handler:    _TourHostService_UpdateTourHost_Handler,
		},
		{
			MethodName: "GetTourHostById",
			Handler:    _TourHostService_GetTourHostById_Handler,
		},
		{
			MethodName: "UpdateHostCardID",
			Handler:    _TourHostService_UpdateHostCardID_Handler,
		},
		{
			MethodName: "UpdateHostBussinessID",
			Handler:    _TourHostService_UpdateHostBussinessID_Handler,
		},
		{
			MethodName: "CreateTourHost",
			Handler:    _TourHostService_CreateTourHost_Handler,
		},
		{
			MethodName: "GetTourHostByCridentials",
			Handler:    _TourHostService_GetTourHostByCridentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/tour-host-service.proto",
}
