// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/notification.proto

package notification

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Service struct {
	// @inject_tag: bson:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	// @inject_tag: bson:"id"
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f16a2954a3d94d2, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Body struct {
	// @inject_tag: bson:"title"
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty" bson:"title"`
	// @inject_tag: bson:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" bson:"message"`
	// @inject_tag: bson:"sender"
	Sender string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty" bson:"sender"`
	// @inject_tag: bson:"time"
	Time string `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty" bson:"time"`
	// @inject_tag: bson:"status"
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty" bson:"status"`
	// @inject_tag: bson:"type"
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty" bson:"type"`
	// @inject_tag: bson:"properties"
	Properties           *Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty" bson:"properties"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f16a2954a3d94d2, []int{1}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Body) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Body) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Body) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Body) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Body) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Body) GetProperties() *Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Properties struct {
	// @inject_tag: bson:"user_id"
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" bson:"user_id"`
	// @inject_tag: bson:"tour_id"
	TourId string `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty" bson:"tour_id"`
	// @inject_tag: bson:"schedule_id"
	ScheduleId string `protobuf:"bytes,3,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty" bson:"schedule_id"`
	// @inject_tag: bson:"order_number"
	OrderNumber string `protobuf:"bytes,4,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty" bson:"order_number"`
	// @inject_tag: bson:"host_id"
	HostId string `protobuf:"bytes,5,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty" bson:"host_id"`
	// @inject_tag: bson:"type_tour"
	TypeTour string `protobuf:"bytes,6,opt,name=type_tour,json=typeTour,proto3" json:"type_tour,omitempty" bson:"type_tour"`
	// @inject_tag: bson:"order_id"
	OrderId string `protobuf:"bytes,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty" bson:"order_id"`
	// @inject_tag: bson:"withdrawal_status"
	WithdrawalStatus string `protobuf:"bytes,8,opt,name=withdrawal_status,json=withdrawalStatus,proto3" json:"withdrawal_status,omitempty" bson:"withdrawal_status"`
	// @inject_tag: bson:"withdrawal_date"
	WithdrawalDate string `protobuf:"bytes,9,opt,name=withdrawal_date,json=withdrawalDate,proto3" json:"withdrawal_date,omitempty" bson:"withdrawal_date"`
	// @inject_tag: bson:"profile_url"
	ProfileUrl string `protobuf:"bytes,10,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty" bson:"profile_url"`
	// @inject_tag: bson:"opponent_of_discussion"
	OpponentOfDiscussion string `protobuf:"bytes,11,opt,name=opponent_of_discussion,json=opponentOfDiscussion,proto3" json:"opponent_of_discussion,omitempty" bson:"opponent_of_discussion"`
	// @inject_tag: bson:"photo_against_discussion"
	PhotoAgainstDiscussion string `protobuf:"bytes,12,opt,name=photo_against_discussion,json=photoAgainstDiscussion,proto3" json:"photo_against_discussion,omitempty" bson:"photo_against_discussion"`
	// @inject_tag: bson:"host_name"
	HostName string `protobuf:"bytes,13,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty" bson:"host_name"`
	// @inject_tag: bson:"schedule_start_date"
	ScheduleStartDate *timestamp.Timestamp `protobuf:"bytes,14,opt,name=schedule_start_date,json=scheduleStartDate,proto3" json:"schedule_start_date,omitempty" bson:"schedule_start_date"`
	// @inject_tag: bson:"schedule_end_date"
	ScheduleEndDate *timestamp.Timestamp `protobuf:"bytes,15,opt,name=schedule_end_date,json=scheduleEndDate,proto3" json:"schedule_end_date,omitempty" bson:"schedule_end_date"`
	// @inject_tag: bson:"discussion_id"
	DiscussionId string `protobuf:"bytes,16,opt,name=discussion_id,json=discussionId,proto3" json:"discussion_id,omitempty" bson:"discussion_id"`
	// @inject_tag: bson:"image_tour_url"
	ImageTourUrl string `protobuf:"bytes,17,opt,name=image_tour_url,json=imageTourUrl,proto3" json:"image_tour_url,omitempty" bson:"image_tour_url"`
	// @inject_tag: bson:"location_tour"
	LocationTour string `protobuf:"bytes,18,opt,name=location_tour,json=locationTour,proto3" json:"location_tour,omitempty" bson:"location_tour"`
	// @inject_tag: bson:"tour_status"
	TourStatus           string   `protobuf:"bytes,19,opt,name=tour_status,json=tourStatus,proto3" json:"tour_status,omitempty" bson:"tour_status"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Properties) Reset()         { *m = Properties{} }
func (m *Properties) String() string { return proto.CompactTextString(m) }
func (*Properties) ProtoMessage()    {}
func (*Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f16a2954a3d94d2, []int{2}
}

func (m *Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Properties.Unmarshal(m, b)
}
func (m *Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Properties.Marshal(b, m, deterministic)
}
func (m *Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Properties.Merge(m, src)
}
func (m *Properties) XXX_Size() int {
	return xxx_messageInfo_Properties.Size(m)
}
func (m *Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_Properties proto.InternalMessageInfo

func (m *Properties) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Properties) GetTourId() string {
	if m != nil {
		return m.TourId
	}
	return ""
}

func (m *Properties) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *Properties) GetOrderNumber() string {
	if m != nil {
		return m.OrderNumber
	}
	return ""
}

func (m *Properties) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *Properties) GetTypeTour() string {
	if m != nil {
		return m.TypeTour
	}
	return ""
}

func (m *Properties) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Properties) GetWithdrawalStatus() string {
	if m != nil {
		return m.WithdrawalStatus
	}
	return ""
}

func (m *Properties) GetWithdrawalDate() string {
	if m != nil {
		return m.WithdrawalDate
	}
	return ""
}

func (m *Properties) GetProfileUrl() string {
	if m != nil {
		return m.ProfileUrl
	}
	return ""
}

func (m *Properties) GetOpponentOfDiscussion() string {
	if m != nil {
		return m.OpponentOfDiscussion
	}
	return ""
}

func (m *Properties) GetPhotoAgainstDiscussion() string {
	if m != nil {
		return m.PhotoAgainstDiscussion
	}
	return ""
}

func (m *Properties) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Properties) GetScheduleStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.ScheduleStartDate
	}
	return nil
}

func (m *Properties) GetScheduleEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.ScheduleEndDate
	}
	return nil
}

func (m *Properties) GetDiscussionId() string {
	if m != nil {
		return m.DiscussionId
	}
	return ""
}

func (m *Properties) GetImageTourUrl() string {
	if m != nil {
		return m.ImageTourUrl
	}
	return ""
}

func (m *Properties) GetLocationTour() string {
	if m != nil {
		return m.LocationTour
	}
	return ""
}

func (m *Properties) GetTourStatus() string {
	if m != nil {
		return m.TourStatus
	}
	return ""
}

type Participants struct {
	// @inject_tag: bson:"user_id"
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" bson:"user_id"`
	// @inject_tag: bson:"device_id"
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" bson:"device_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Participants) Reset()         { *m = Participants{} }
func (m *Participants) String() string { return proto.CompactTextString(m) }
func (*Participants) ProtoMessage()    {}
func (*Participants) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f16a2954a3d94d2, []int{3}
}

func (m *Participants) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Participants.Unmarshal(m, b)
}
func (m *Participants) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Participants.Marshal(b, m, deterministic)
}
func (m *Participants) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participants.Merge(m, src)
}
func (m *Participants) XXX_Size() int {
	return xxx_messageInfo_Participants.Size(m)
}
func (m *Participants) XXX_DiscardUnknown() {
	xxx_messageInfo_Participants.DiscardUnknown(m)
}

var xxx_messageInfo_Participants proto.InternalMessageInfo

func (m *Participants) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Participants) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type Notification struct {
	// @inject_tag: bson:"service"
	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty" bson:"service"`
	// @inject_tag: bson:"body"
	Body *Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty" bson:"body"`
	// @inject_tag: bson:"created_at"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at"`
	// @inject_tag: bson:"participants"
	Participants         []*Participants `protobuf:"bytes,4,rep,name=participants,proto3" json:"participants,omitempty" bson:"participants"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f16a2954a3d94d2, []int{4}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Notification) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Notification) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Notification) GetParticipants() []*Participants {
	if m != nil {
		return m.Participants
	}
	return nil
}

type NotificationResponse struct {
	Title                string          `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Code                 int32           `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 []*Notification `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NotificationResponse) Reset()         { *m = NotificationResponse{} }
func (m *NotificationResponse) String() string { return proto.CompactTextString(m) }
func (*NotificationResponse) ProtoMessage()    {}
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f16a2954a3d94d2, []int{5}
}

func (m *NotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationResponse.Unmarshal(m, b)
}
func (m *NotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationResponse.Marshal(b, m, deterministic)
}
func (m *NotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationResponse.Merge(m, src)
}
func (m *NotificationResponse) XXX_Size() int {
	return xxx_messageInfo_NotificationResponse.Size(m)
}
func (m *NotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationResponse proto.InternalMessageInfo

func (m *NotificationResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NotificationResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *NotificationResponse) GetData() []*Notification {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "notification.Service")
	proto.RegisterType((*Body)(nil), "notification.Body")
	proto.RegisterType((*Properties)(nil), "notification.Properties")
	proto.RegisterType((*Participants)(nil), "notification.Participants")
	proto.RegisterType((*Notification)(nil), "notification.Notification")
	proto.RegisterType((*NotificationResponse)(nil), "notification.NotificationResponse")
}

func init() { proto.RegisterFile("protobuf/notification.proto", fileDescriptor_7f16a2954a3d94d2) }

var fileDescriptor_7f16a2954a3d94d2 = []byte{
	// 824 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x8e, 0x1b, 0x45,
	0x10, 0x96, 0xbd, 0xfe, 0x2d, 0x7b, 0xed, 0x6c, 0xef, 0xb2, 0x0c, 0x36, 0xd2, 0x9a, 0x49, 0x14,
	0xa2, 0x20, 0x6c, 0x61, 0x38, 0x04, 0x0e, 0x48, 0x81, 0x05, 0x64, 0x0e, 0x4b, 0x34, 0x1b, 0xce,
	0xa3, 0xb6, 0xbb, 0x6d, 0xb7, 0x34, 0x9e, 0x1e, 0x75, 0xf7, 0x24, 0xb2, 0x20, 0x17, 0x1e, 0x01,
	0x5e, 0x8a, 0x3b, 0x6f, 0x80, 0x78, 0x0c, 0x0e, 0xa8, 0xab, 0x7b, 0xec, 0x19, 0x29, 0x18, 0x6e,
	0x53, 0x5f, 0x7d, 0x55, 0xe5, 0xaf, 0xaa, 0xba, 0x0c, 0xe3, 0x4c, 0x49, 0x23, 0x97, 0xf9, 0x7a,
	0x96, 0x4a, 0x23, 0xd6, 0x62, 0x45, 0x8d, 0x90, 0xe9, 0x14, 0x51, 0xd2, 0x2f, 0x63, 0xa3, 0x9b,
	0x8d, 0x94, 0x9b, 0x84, 0xcf, 0x0e, 0x11, 0x46, 0xec, 0xb8, 0x36, 0x74, 0x97, 0x39, 0xfa, 0xe8,
	0x7d, 0x4f, 0xa0, 0x99, 0x98, 0xd1, 0x34, 0x95, 0x06, 0xe3, 0xb4, 0xf3, 0x86, 0x1f, 0x43, 0xfb,
	0x9e, 0xab, 0x57, 0x62, 0xc5, 0x09, 0x81, 0x46, 0x4a, 0x77, 0x3c, 0xa8, 0x4d, 0x6a, 0x4f, 0xba,
	0x11, 0x7e, 0x93, 0x01, 0xd4, 0x05, 0x0b, 0xea, 0x88, 0xd4, 0x05, 0x0b, 0x7f, 0xaf, 0x41, 0xe3,
	0x2b, 0xc9, 0xf6, 0xe4, 0x0a, 0x9a, 0x46, 0x98, 0xa4, 0x60, 0x3b, 0x83, 0x04, 0xd0, 0xde, 0x71,
	0xad, 0xe9, 0x86, 0xfb, 0x98, 0xc2, 0x24, 0xd7, 0xd0, 0xd2, 0x3c, 0x65, 0x5c, 0x05, 0x67, 0xe8,
	0xf0, 0x96, 0x2d, 0x6a, 0x7f, 0x70, 0xd0, 0x70, 0x45, 0xed, 0x37, 0x72, 0x0d, 0x35, 0xb9, 0x0e,
	0x9a, 0x9e, 0x8b, 0x16, 0x72, 0xf7, 0x19, 0x0f, 0x5a, 0x9e, 0xbb, 0xcf, 0x38, 0x79, 0x06, 0x90,
	0x29, 0x99, 0x71, 0x65, 0x04, 0xd7, 0x41, 0x7b, 0x52, 0x7b, 0xd2, 0x9b, 0x07, 0xd3, 0x4a, 0xd7,
	0x5e, 0x1c, 0xfc, 0x51, 0x89, 0x1b, 0xfe, 0xdd, 0x04, 0x38, 0xba, 0xc8, 0xbb, 0xd0, 0xce, 0x35,
	0x57, 0xb1, 0x60, 0x5e, 0x52, 0xcb, 0x9a, 0x0b, 0x66, 0x1d, 0x46, 0xe6, 0xe8, 0x70, 0x9a, 0x5a,
	0xd6, 0x5c, 0x30, 0x72, 0x03, 0x3d, 0xbd, 0xda, 0x72, 0x96, 0x27, 0xdc, 0x3a, 0x9d, 0x2e, 0x28,
	0xa0, 0x05, 0x23, 0x1f, 0x40, 0x5f, 0x2a, 0xc6, 0x55, 0x9c, 0xe6, 0xbb, 0x25, 0x57, 0x5e, 0x63,
	0x0f, 0xb1, 0x3b, 0x84, 0x6c, 0xf2, 0xad, 0xd4, 0xc6, 0xc6, 0x7b, 0xad, 0xd6, 0x5c, 0x30, 0x32,
	0x86, 0xae, 0xd5, 0x17, 0xdb, 0x5a, 0x5e, 0x70, 0xc7, 0x02, 0x2f, 0x65, 0xae, 0xc8, 0x7b, 0xd0,
	0x71, 0x89, 0x05, 0x43, 0xc9, 0xdd, 0xa8, 0x8d, 0xf6, 0x82, 0x91, 0x8f, 0xe0, 0xe2, 0xb5, 0x30,
	0x5b, 0xa6, 0xe8, 0x6b, 0x9a, 0xc4, 0xbe, 0x8d, 0x1d, 0xe4, 0x3c, 0x38, 0x3a, 0xee, 0x5d, 0x43,
	0x3f, 0x84, 0x61, 0x89, 0xcc, 0xa8, 0xe1, 0x41, 0x17, 0xa9, 0x83, 0x23, 0x7c, 0x4b, 0x0d, 0xb7,
	0x52, 0x33, 0x25, 0xd7, 0x22, 0xe1, 0x71, 0xae, 0x92, 0x00, 0x9c, 0x54, 0x0f, 0xfd, 0xa8, 0x12,
	0xf2, 0x19, 0x5c, 0xcb, 0x2c, 0x93, 0x29, 0x4f, 0x4d, 0x2c, 0xd7, 0x31, 0x13, 0x7a, 0x95, 0x6b,
	0x2d, 0x64, 0x1a, 0xf4, 0x90, 0x7b, 0x55, 0x78, 0x7f, 0x58, 0xdf, 0x1e, 0x7c, 0xe4, 0x19, 0x04,
	0xd9, 0x56, 0x1a, 0x19, 0xd3, 0x0d, 0x15, 0xa9, 0x36, 0xe5, 0xb8, 0x3e, 0xc6, 0x5d, 0xa3, 0xff,
	0xb9, 0x73, 0x97, 0x22, 0xc7, 0xd0, 0xc5, 0xbe, 0xe1, 0xc2, 0x9e, 0xbb, 0xf6, 0x58, 0xe0, 0xce,
	0x2e, 0xed, 0xf7, 0x70, 0x79, 0x18, 0x8c, 0x36, 0x54, 0x19, 0x27, 0x6d, 0x80, 0xcb, 0x31, 0x9a,
	0xba, 0xf7, 0x30, 0x2d, 0x1e, 0xcc, 0xf4, 0x65, 0xf1, 0x60, 0xa2, 0x8b, 0x22, 0xec, 0xde, 0x46,
	0xa1, 0xf2, 0x6f, 0xe1, 0x00, 0xc6, 0x3c, 0x65, 0x2e, 0xd3, 0xf0, 0x3f, 0x33, 0x0d, 0x8b, 0xa0,
	0x6f, 0x52, 0x86, 0x79, 0x1e, 0xc2, 0xf9, 0x51, 0x9c, 0x9d, 0xdb, 0x03, 0xfc, 0xd1, 0xfd, 0x23,
	0xb8, 0x60, 0xe4, 0x11, 0x0c, 0xc4, 0x8e, 0x6e, 0xdc, 0xd4, 0xb1, 0xd3, 0x17, 0x8e, 0x85, 0xa8,
	0x1d, 0xbd, 0xed, 0xf5, 0x43, 0x38, 0x4f, 0xa4, 0xdb, 0x6d, 0xb7, 0x1e, 0xc4, 0x91, 0x0a, 0x10,
	0x57, 0xe4, 0x06, 0x7a, 0x98, 0xc4, 0x6f, 0xc0, 0xa5, 0x9b, 0x98, 0x85, 0xdc, 0xec, 0xc3, 0x5b,
	0xe8, 0xbf, 0xa0, 0xca, 0x88, 0x95, 0xc8, 0x68, 0x6a, 0x4e, 0xec, 0xff, 0x18, 0xba, 0x8c, 0xdb,
	0x03, 0x71, 0x7c, 0x01, 0x1d, 0x07, 0x2c, 0x58, 0xf8, 0x67, 0x0d, 0xfa, 0x77, 0xa5, 0xc7, 0x46,
	0x66, 0xd0, 0xd6, 0xee, 0x9e, 0x60, 0x9a, 0xde, 0xfc, 0x9d, 0xea, 0x63, 0xf4, 0xc7, 0x26, 0x2a,
	0x58, 0xe4, 0x31, 0x34, 0x96, 0x92, 0xed, 0x31, 0x73, 0x6f, 0x4e, 0xaa, 0x6c, 0x7b, 0x6a, 0x22,
	0xf4, 0x93, 0xcf, 0x01, 0x56, 0x8a, 0x53, 0xc3, 0x59, 0x4c, 0x0d, 0x3e, 0xb6, 0xd3, 0x13, 0xe8,
	0x7a, 0xf6, 0x73, 0x43, 0xbe, 0x84, 0x7e, 0x56, 0x92, 0x1a, 0x34, 0x26, 0x67, 0x18, 0x5c, 0xbd,
	0x12, 0x25, 0x46, 0x54, 0xe1, 0x87, 0x19, 0x5c, 0x95, 0x35, 0x46, 0x5c, 0x67, 0x32, 0xd5, 0xfc,
	0x5f, 0x6e, 0x20, 0x81, 0xc6, 0x4a, 0x32, 0x77, 0x00, 0x9b, 0x11, 0x7e, 0x93, 0x29, 0x34, 0x18,
	0x35, 0x34, 0x38, 0x7b, 0x5b, 0xe5, 0x4a, 0x6e, 0xe4, 0xcd, 0x7f, 0xad, 0xc3, 0x65, 0x19, 0x2e,
	0x4e, 0xf4, 0xcf, 0x40, 0xbe, 0x46, 0x59, 0x95, 0x9e, 0x9f, 0xc8, 0x37, 0x0a, 0x4f, 0xd4, 0xf2,
	0x3a, 0xc2, 0xc7, 0xbf, 0xfc, 0xf1, 0xd7, 0x6f, 0xf5, 0x49, 0x38, 0xc6, 0xff, 0x88, 0x57, 0x9f,
	0x54, 0xfe, 0x74, 0x66, 0xae, 0x8f, 0x5f, 0xd4, 0x9e, 0x92, 0x37, 0x30, 0xfc, 0x8e, 0x9b, 0x53,
	0xa5, 0xcb, 0x4d, 0xfc, 0x5f, 0xa5, 0x9f, 0x62, 0xe9, 0x47, 0x24, 0x7c, 0x6b, 0xe9, 0x0d, 0x37,
	0xb3, 0x9f, 0xfc, 0x56, 0xbe, 0x59, 0xb6, 0x70, 0xca, 0x9f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x41, 0x33, 0x0c, 0xd4, 0x1d, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationServiceClient interface {
	CreateNotification(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*NotificationResponse, error)
	GetNotification(ctx context.Context, in *Participants, opts ...grpc.CallOption) (*NotificationResponse, error)
}

type notificationServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotificationServiceClient(cc *grpc.ClientConn) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) CreateNotification(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*NotificationResponse, error) {
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/CreateNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotification(ctx context.Context, in *Participants, opts ...grpc.CallOption) (*NotificationResponse, error) {
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/GetNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
type NotificationServiceServer interface {
	CreateNotification(context.Context, *Notification) (*NotificationResponse, error)
	GetNotification(context.Context, *Participants) (*NotificationResponse, error)
}

// UnimplementedNotificationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (*UnimplementedNotificationServiceServer) CreateNotification(ctx context.Context, req *Notification) (*NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotification not implemented")
}
func (*UnimplementedNotificationServiceServer) GetNotification(ctx context.Context, req *Participants) (*NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotification not implemented")
}

func RegisterNotificationServiceServer(s *grpc.Server, srv NotificationServiceServer) {
	s.RegisterService(&_NotificationService_serviceDesc, srv)
}

func _NotificationService_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Notification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/CreateNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNotification(ctx, req.(*Notification))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Participants)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/GetNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotification(ctx, req.(*Participants))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNotification",
			Handler:    _NotificationService_CreateNotification_Handler,
		},
		{
			MethodName: "GetNotification",
			Handler:    _NotificationService_GetNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/notification.proto",
}
