// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delivery/grpc/user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender               string               `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ProfilePictureUrl    string               `protobuf:"bytes,9,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	IsVerified           bool                 `protobuf:"varint,10,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	IsSuspended          bool                 `protobuf:"varint,11,opt,name=is_suspended,json=isSuspended,proto3" json:"is_suspended,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetProfilePictureUrl() string {
	if m != nil {
		return m.ProfilePictureUrl
	}
	return ""
}

func (m *User) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *User) GetIsSuspended() bool {
	if m != nil {
		return m.IsSuspended
	}
	return false
}

type CreateUserRequest struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string               `protobuf:"bytes,6,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender               string               `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *CreateUserRequest) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *CreateUserRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *CreateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateUserResponse struct {
	Data                 *CreateUserRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetData() *CreateUserRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

type EmailVerificationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VerificationToken    string   `protobuf:"bytes,2,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailVerificationRequest) Reset()         { *m = EmailVerificationRequest{} }
func (m *EmailVerificationRequest) String() string { return proto.CompactTextString(m) }
func (*EmailVerificationRequest) ProtoMessage()    {}
func (*EmailVerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{3}
}

func (m *EmailVerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailVerificationRequest.Unmarshal(m, b)
}
func (m *EmailVerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailVerificationRequest.Marshal(b, m, deterministic)
}
func (m *EmailVerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailVerificationRequest.Merge(m, src)
}
func (m *EmailVerificationRequest) XXX_Size() int {
	return xxx_messageInfo_EmailVerificationRequest.Size(m)
}
func (m *EmailVerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailVerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailVerificationRequest proto.InternalMessageInfo

func (m *EmailVerificationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailVerificationRequest) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

type EmailVerificationResponse struct {
	Data                 *EmailVerificationRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *EmailVerificationResponse) Reset()         { *m = EmailVerificationResponse{} }
func (m *EmailVerificationResponse) String() string { return proto.CompactTextString(m) }
func (*EmailVerificationResponse) ProtoMessage()    {}
func (*EmailVerificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{4}
}

func (m *EmailVerificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailVerificationResponse.Unmarshal(m, b)
}
func (m *EmailVerificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailVerificationResponse.Marshal(b, m, deterministic)
}
func (m *EmailVerificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailVerificationResponse.Merge(m, src)
}
func (m *EmailVerificationResponse) XXX_Size() int {
	return xxx_messageInfo_EmailVerificationResponse.Size(m)
}
func (m *EmailVerificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailVerificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailVerificationResponse proto.InternalMessageInfo

func (m *EmailVerificationResponse) GetData() *EmailVerificationRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateUserRequest struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string               `protobuf:"bytes,6,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender               string               `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ProfilePictureUrl    string               `protobuf:"bytes,10,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateUserRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *UpdateUserRequest) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *UpdateUserRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UpdateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UpdateUserRequest) GetProfilePictureUrl() string {
	if m != nil {
		return m.ProfilePictureUrl
	}
	return ""
}

type UpdateUserSettingRequest struct {
	UserUid              string                `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	EmailNotification    *wrappers.BoolValue   `protobuf:"bytes,2,opt,name=email_notification,json=emailNotification,proto3" json:"email_notification,omitempty"`
	PushNotification     *wrappers.BoolValue   `protobuf:"bytes,3,opt,name=push_notification,json=pushNotification,proto3" json:"push_notification,omitempty"`
	CurrencyUid          *wrappers.StringValue `protobuf:"bytes,4,opt,name=currency_uid,json=currencyUid,proto3" json:"currency_uid,omitempty"`
	LanguageUid          *wrappers.StringValue `protobuf:"bytes,5,opt,name=language_uid,json=languageUid,proto3" json:"language_uid,omitempty"`
	PaymentTypeUid       *wrappers.StringValue `protobuf:"bytes,6,opt,name=payment_type_uid,json=paymentTypeUid,proto3" json:"payment_type_uid,omitempty"`
	CreditCardNumber     *wrappers.StringValue `protobuf:"bytes,7,opt,name=CreditCardNumber,proto3" json:"CreditCardNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserSettingRequest) Reset()         { *m = UpdateUserSettingRequest{} }
func (m *UpdateUserSettingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserSettingRequest) ProtoMessage()    {}
func (*UpdateUserSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{6}
}

func (m *UpdateUserSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserSettingRequest.Unmarshal(m, b)
}
func (m *UpdateUserSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserSettingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserSettingRequest.Merge(m, src)
}
func (m *UpdateUserSettingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserSettingRequest.Size(m)
}
func (m *UpdateUserSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserSettingRequest proto.InternalMessageInfo

func (m *UpdateUserSettingRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *UpdateUserSettingRequest) GetEmailNotification() *wrappers.BoolValue {
	if m != nil {
		return m.EmailNotification
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetPushNotification() *wrappers.BoolValue {
	if m != nil {
		return m.PushNotification
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetCurrencyUid() *wrappers.StringValue {
	if m != nil {
		return m.CurrencyUid
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetLanguageUid() *wrappers.StringValue {
	if m != nil {
		return m.LanguageUid
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetPaymentTypeUid() *wrappers.StringValue {
	if m != nil {
		return m.PaymentTypeUid
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetCreditCardNumber() *wrappers.StringValue {
	if m != nil {
		return m.CreditCardNumber
	}
	return nil
}

type Filter struct {
	Field                string   `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=Operator,proto3" json:"Operator,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{7}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Filter) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Filter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BrowseRequest struct {
	Filters              []*Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Limit                int32     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32     `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BrowseRequest) Reset()         { *m = BrowseRequest{} }
func (m *BrowseRequest) String() string { return proto.CompactTextString(m) }
func (*BrowseRequest) ProtoMessage()    {}
func (*BrowseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{8}
}

func (m *BrowseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseRequest.Unmarshal(m, b)
}
func (m *BrowseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseRequest.Marshal(b, m, deterministic)
}
func (m *BrowseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseRequest.Merge(m, src)
}
func (m *BrowseRequest) XXX_Size() int {
	return xxx_messageInfo_BrowseRequest.Size(m)
}
func (m *BrowseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseRequest proto.InternalMessageInfo

func (m *BrowseRequest) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *BrowseRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *BrowseRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type UpdateUserResponse struct {
	Data                 *UpdateUserRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{9}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetData() *UpdateUserRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateUserSettingResponse struct {
	Data                 *UpdateUserSettingRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UpdateUserSettingResponse) Reset()         { *m = UpdateUserSettingResponse{} }
func (m *UpdateUserSettingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserSettingResponse) ProtoMessage()    {}
func (*UpdateUserSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{10}
}

func (m *UpdateUserSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserSettingResponse.Unmarshal(m, b)
}
func (m *UpdateUserSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserSettingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserSettingResponse.Merge(m, src)
}
func (m *UpdateUserSettingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserSettingResponse.Size(m)
}
func (m *UpdateUserSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserSettingResponse proto.InternalMessageInfo

func (m *UpdateUserSettingResponse) GetData() *UpdateUserSettingRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

type BrowseUserResponse struct {
	Data                 []*User  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrowseUserResponse) Reset()         { *m = BrowseUserResponse{} }
func (m *BrowseUserResponse) String() string { return proto.CompactTextString(m) }
func (*BrowseUserResponse) ProtoMessage()    {}
func (*BrowseUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{11}
}

func (m *BrowseUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseUserResponse.Unmarshal(m, b)
}
func (m *BrowseUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseUserResponse.Marshal(b, m, deterministic)
}
func (m *BrowseUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseUserResponse.Merge(m, src)
}
func (m *BrowseUserResponse) XXX_Size() int {
	return xxx_messageInfo_BrowseUserResponse.Size(m)
}
func (m *BrowseUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseUserResponse proto.InternalMessageInfo

func (m *BrowseUserResponse) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

type Error struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{12}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Error) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetUserByCredentialsRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByCredentialsRequest) Reset()         { *m = GetUserByCredentialsRequest{} }
func (m *GetUserByCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByCredentialsRequest) ProtoMessage()    {}
func (*GetUserByCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{13}
}

func (m *GetUserByCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByCredentialsRequest.Unmarshal(m, b)
}
func (m *GetUserByCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByCredentialsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByCredentialsRequest.Merge(m, src)
}
func (m *GetUserByCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByCredentialsRequest.Size(m)
}
func (m *GetUserByCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByCredentialsRequest proto.InternalMessageInfo

func (m *GetUserByCredentialsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserByCredentialsRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetUserByCredentialsResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByCredentialsResponse) Reset()         { *m = GetUserByCredentialsResponse{} }
func (m *GetUserByCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByCredentialsResponse) ProtoMessage()    {}
func (*GetUserByCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{14}
}

func (m *GetUserByCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByCredentialsResponse.Unmarshal(m, b)
}
func (m *GetUserByCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByCredentialsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByCredentialsResponse.Merge(m, src)
}
func (m *GetUserByCredentialsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByCredentialsResponse.Size(m)
}
func (m *GetUserByCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByCredentialsResponse proto.InternalMessageInfo

func (m *GetUserByCredentialsResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetUserRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{15}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetUserResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{16}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.CreateUserResponse")
	proto.RegisterType((*EmailVerificationRequest)(nil), "user.EmailVerificationRequest")
	proto.RegisterType((*EmailVerificationResponse)(nil), "user.EmailVerificationResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserSettingRequest)(nil), "user.UpdateUserSettingRequest")
	proto.RegisterType((*Filter)(nil), "user.Filter")
	proto.RegisterType((*BrowseRequest)(nil), "user.BrowseRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "user.UpdateUserResponse")
	proto.RegisterType((*UpdateUserSettingResponse)(nil), "user.UpdateUserSettingResponse")
	proto.RegisterType((*BrowseUserResponse)(nil), "user.BrowseUserResponse")
	proto.RegisterType((*Error)(nil), "user.Error")
	proto.RegisterType((*GetUserByCredentialsRequest)(nil), "user.GetUserByCredentialsRequest")
	proto.RegisterType((*GetUserByCredentialsResponse)(nil), "user.GetUserByCredentialsResponse")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user.GetUserResponse")
}

func init() { proto.RegisterFile("delivery/grpc/user/user.proto", fileDescriptor_2ce0ae0e1358080f) }

var fileDescriptor_2ce0ae0e1358080f = []byte{
	// 1035 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0x97, 0xed, 0x38, 0xb1, 0x9f, 0x93, 0x12, 0x4f, 0x53, 0xd8, 0xb8, 0x69, 0x92, 0xae, 0x10,
	0x8a, 0x82, 0xb0, 0x55, 0x17, 0x38, 0xf4, 0xd0, 0x8a, 0x44, 0x4d, 0xe1, 0x92, 0x54, 0x9b, 0xa4,
	0x12, 0x07, 0xb4, 0x9a, 0x78, 0xdf, 0x3a, 0x23, 0xd6, 0x3b, 0xcb, 0xcc, 0x6c, 0x22, 0x0b, 0x21,
	0x21, 0xbe, 0x02, 0x1f, 0x89, 0x8f, 0xc0, 0x99, 0x13, 0x7c, 0x03, 0xc4, 0x1d, 0xcd, 0x9f, 0x4d,
	0xec, 0xae, 0xed, 0x46, 0x70, 0xe0, 0xc2, 0xc5, 0xf2, 0x9b, 0xf7, 0xde, 0x6f, 0xe6, 0xfd, 0x7e,
	0x6f, 0xde, 0x2c, 0x3c, 0x8a, 0x30, 0x61, 0x57, 0x28, 0xc6, 0xbd, 0xa1, 0xc8, 0x06, 0xbd, 0x5c,
	0xa2, 0x30, 0x3f, 0xdd, 0x4c, 0x70, 0xc5, 0xc9, 0x92, 0xfe, 0xdf, 0xd9, 0x19, 0x72, 0x3e, 0x4c,
	0xb0, 0x67, 0xd6, 0x2e, 0xf2, 0xb8, 0xa7, 0xd8, 0x08, 0xa5, 0xa2, 0xa3, 0xcc, 0x86, 0x75, 0xb6,
	0x5c, 0x00, 0xcd, 0x58, 0x8f, 0xa6, 0x29, 0x57, 0x54, 0x31, 0x9e, 0x4a, 0xe7, 0xdd, 0x7e, 0x3b,
	0xfd, 0x5a, 0xd0, 0x2c, 0x43, 0xe1, 0xfc, 0xfe, 0x5f, 0x55, 0x58, 0x3a, 0x97, 0x28, 0xc8, 0x3a,
	0xd4, 0x72, 0x16, 0x79, 0x95, 0xdd, 0xca, 0x5e, 0x33, 0xd0, 0x7f, 0xc9, 0x23, 0x80, 0x98, 0x09,
	0xa9, 0xc2, 0x94, 0x8e, 0xd0, 0xab, 0x1a, 0x47, 0xd3, 0xac, 0x1c, 0xd3, 0x11, 0x92, 0x87, 0xd0,
	0x4c, 0x68, 0xe1, 0xad, 0x19, 0x6f, 0x43, 0x2f, 0x18, 0xe7, 0x06, 0xd4, 0x71, 0x44, 0x59, 0xe2,
	0x2d, 0x19, 0x87, 0x35, 0x48, 0x07, 0x1a, 0x19, 0x95, 0xf2, 0x9a, 0x8b, 0xc8, 0xab, 0xdb, 0x8c,
	0xc2, 0x26, 0xcf, 0x61, 0x2d, 0xa2, 0x0a, 0x43, 0x1e, 0x87, 0x17, 0x4c, 0xa8, 0x4b, 0x6f, 0x79,
	0xb7, 0xb2, 0xd7, 0xea, 0x77, 0xba, 0xb6, 0x80, 0x6e, 0x51, 0x40, 0xf7, 0xac, 0xa8, 0x3f, 0x68,
	0xe9, 0x84, 0x93, 0xf8, 0x40, 0x87, 0x93, 0xf7, 0x61, 0x79, 0x88, 0x69, 0x84, 0xc2, 0x5b, 0x31,
	0xc8, 0xce, 0x22, 0x8f, 0x61, 0x35, 0xbb, 0xe4, 0x29, 0x86, 0x69, 0x3e, 0xba, 0x40, 0xe1, 0x35,
	0x8c, 0xb7, 0x65, 0xd6, 0x8e, 0xcd, 0x12, 0xe9, 0xc2, 0xfd, 0x4c, 0xf0, 0x98, 0x25, 0x18, 0x66,
	0x6c, 0xa0, 0x72, 0x81, 0x61, 0x2e, 0x12, 0xaf, 0x69, 0x22, 0xdb, 0xce, 0xf5, 0xda, 0x7a, 0xce,
	0x45, 0x42, 0x76, 0xa0, 0xc5, 0x64, 0x78, 0x85, 0x82, 0xc5, 0x0c, 0x23, 0x0f, 0x76, 0x2b, 0x7b,
	0x8d, 0x00, 0x98, 0x7c, 0xe3, 0x56, 0xf4, 0x9e, 0x4c, 0x86, 0x32, 0x97, 0x99, 0x3e, 0x43, 0xe4,
	0xb5, 0x4c, 0x44, 0x8b, 0xc9, 0xd3, 0x62, 0xc9, 0xff, 0xa5, 0x0a, 0xed, 0x43, 0x81, 0x54, 0xa1,
	0x66, 0x3f, 0xc0, 0xef, 0x72, 0x94, 0xea, 0x3f, 0x17, 0xe1, 0x29, 0x3c, 0x28, 0xfe, 0x87, 0x03,
	0x9e, 0xc6, 0x4c, 0x8c, 0x4c, 0x37, 0x19, 0x31, 0x9a, 0xc1, 0x46, 0xe1, 0x3c, 0x9c, 0xf0, 0x95,
	0x95, 0x5b, 0xf9, 0xa7, 0xca, 0x35, 0x16, 0x2a, 0xd7, 0x2c, 0x29, 0xe7, 0x7f, 0x01, 0x64, 0x92,
	0x44, 0x99, 0xf1, 0x54, 0x22, 0xf9, 0x18, 0x96, 0x22, 0xaa, 0xa8, 0xa1, 0xb1, 0xd5, 0xff, 0xa0,
	0x6b, 0xee, 0x54, 0x89, 0xec, 0xc0, 0x04, 0xf9, 0x21, 0x78, 0x2f, 0x35, 0x2f, 0x56, 0xbc, 0x81,
	0x29, 0xa9, 0x90, 0xe3, 0x86, 0xc0, 0xca, 0x24, 0x81, 0x9f, 0x00, 0xb9, 0x9a, 0x08, 0x0e, 0x15,
	0xff, 0x16, 0x53, 0x27, 0x4d, 0x7b, 0xd2, 0x73, 0xa6, 0x1d, 0xfe, 0x09, 0x6c, 0xce, 0xd8, 0xc0,
	0x1d, 0xb5, 0x3f, 0x75, 0xd4, 0x6d, 0x7b, 0xd4, 0x79, 0xe7, 0x71, 0x27, 0xfe, 0xb3, 0x0a, 0xed,
	0xf3, 0x2c, 0xfa, 0xbf, 0x75, 0xfe, 0x4d, 0xeb, 0xcc, 0xbb, 0xf4, 0x30, 0xe7, 0xd2, 0xfb, 0xbf,
	0xd5, 0xc0, 0xbb, 0x65, 0xfd, 0x14, 0x95, 0x62, 0xe9, 0xb0, 0x20, 0x7f, 0x13, 0x1a, 0x5a, 0xb9,
	0xf0, 0x56, 0x81, 0x15, 0x6d, 0x9f, 0xb3, 0x88, 0x7c, 0x05, 0xc4, 0x90, 0x17, 0xa6, 0x5c, 0xdd,
	0x08, 0x6a, 0xd4, 0x98, 0x55, 0xe7, 0x01, 0xe7, 0xc9, 0x1b, 0x9a, 0xe4, 0x18, 0xb4, 0x4d, 0xd6,
	0xf1, 0x44, 0x12, 0x79, 0x05, 0xed, 0x2c, 0x97, 0x97, 0xd3, 0x48, 0xb5, 0x77, 0x22, 0xad, 0xeb,
	0xa4, 0x29, 0xa0, 0x17, 0xb0, 0x3a, 0xc8, 0x85, 0xc0, 0x74, 0x30, 0x36, 0x47, 0x5e, 0x32, 0x18,
	0x5b, 0x25, 0x8c, 0x53, 0x25, 0x58, 0x3a, 0xb4, 0x28, 0xad, 0x22, 0x43, 0x17, 0xf5, 0x02, 0x56,
	0x13, 0x9a, 0x0e, 0x73, 0x3a, 0x44, 0x03, 0x50, 0xbf, 0x0b, 0x40, 0x91, 0xa1, 0x01, 0x8e, 0x60,
	0x3d, 0xa3, 0xe3, 0x11, 0xa6, 0x2a, 0x54, 0xe3, 0xcc, 0x82, 0x2c, 0xdf, 0x01, 0xe4, 0x9e, 0xcb,
	0x3a, 0x1b, 0x67, 0x06, 0xe7, 0x4b, 0x58, 0x3f, 0x14, 0x18, 0x31, 0x75, 0x48, 0x45, 0x64, 0x95,
	0x75, 0x3d, 0xb4, 0x18, 0xa7, 0x94, 0xe5, 0xbf, 0x86, 0xe5, 0x23, 0x96, 0x28, 0x14, 0xba, 0xf7,
	0x8f, 0x18, 0x26, 0x85, 0x92, 0xd6, 0xd0, 0xbd, 0x7f, 0x92, 0xa1, 0xa0, 0x8a, 0x0b, 0x77, 0x97,
	0x6e, 0x6c, 0x9d, 0x61, 0x60, 0xdd, 0x35, 0xb2, 0x86, 0x8f, 0xb0, 0x76, 0x20, 0xf8, 0xb5, 0xc4,
	0xa2, 0x4b, 0x3e, 0x82, 0x95, 0xd8, 0x6c, 0x21, 0xbd, 0xca, 0x6e, 0x6d, 0xaf, 0xd5, 0x5f, 0xb5,
	0xf7, 0xdd, 0xee, 0x1b, 0x14, 0x4e, 0x0d, 0x97, 0xb0, 0x11, 0x53, 0x66, 0x9f, 0x7a, 0x60, 0x0d,
	0xdd, 0xeb, 0x3c, 0x8e, 0x25, 0x2a, 0xb3, 0x4b, 0x3d, 0x70, 0x96, 0x9e, 0x81, 0x93, 0xd3, 0x60,
	0xd1, 0x0c, 0x2c, 0x4d, 0x0d, 0x37, 0x51, 0x4e, 0x60, 0x73, 0x46, 0x6b, 0x2f, 0x1a, 0x51, 0xf3,
	0x6e, 0x82, 0x03, 0xfc, 0x14, 0x88, 0x2d, 0x7d, 0xea, 0x4c, 0xdb, 0x37, 0x48, 0xba, 0x78, 0x70,
	0x48, 0x3a, 0xc2, 0x66, 0x7d, 0x06, 0xf5, 0x97, 0x42, 0x70, 0xa1, 0x4b, 0x95, 0x3c, 0x17, 0x03,
	0x74, 0x12, 0x38, 0x4b, 0x13, 0xa3, 0x98, 0x4a, 0x8a, 0x61, 0x66, 0x0d, 0xff, 0x04, 0x1e, 0xbe,
	0x42, 0xa5, 0x71, 0x0e, 0xc6, 0x5a, 0x56, 0x4c, 0x15, 0xa3, 0x89, 0x5c, 0x3c, 0xc4, 0x27, 0x47,
	0x59, 0x75, 0x7a, 0x94, 0xf9, 0xcf, 0x61, 0x6b, 0x36, 0x60, 0xa9, 0x8e, 0xca, 0xcc, 0x3a, 0x7c,
	0xb8, 0xe7, 0xf2, 0xe7, 0x0e, 0x67, 0xff, 0x09, 0xbc, 0x77, 0x13, 0x73, 0x37, 0xd8, 0xfe, 0xef,
	0x35, 0x68, 0x59, 0xc6, 0xc5, 0x15, 0x1b, 0x20, 0xf9, 0x1a, 0xe0, 0xf6, 0x51, 0x23, 0xf3, 0x9e,
	0xb9, 0x8e, 0x57, 0x76, 0xd8, 0x0d, 0x7d, 0xef, 0xa7, 0x5f, 0xff, 0xf8, 0xb9, 0x4a, 0xfc, 0x35,
	0xf3, 0xed, 0x78, 0xf5, 0xc4, 0x7c, 0x7c, 0xca, 0x67, 0x95, 0x7d, 0x12, 0x02, 0xdc, 0x2a, 0x4c,
	0xe6, 0x75, 0x4f, 0x01, 0x5d, 0x6e, 0x3f, 0x7f, 0xdb, 0x40, 0x7b, 0xfd, 0xfb, 0x53, 0xd0, 0xbd,
	0xef, 0x73, 0x16, 0xfd, 0xa0, 0x37, 0xf8, 0x1c, 0x56, 0x5c, 0xf9, 0x64, 0xc3, 0x82, 0x4c, 0x33,
	0xd6, 0x79, 0xf0, 0xd6, 0xaa, 0xe3, 0xe8, 0x1b, 0xd8, 0x98, 0x25, 0x0d, 0x79, 0x3c, 0x15, 0x3e,
	0xab, 0x0f, 0x3a, 0xfe, 0xa2, 0x10, 0x07, 0xff, 0x63, 0x05, 0xda, 0xa5, 0xd7, 0x97, 0xbc, 0xe3,
	0x59, 0xee, 0xec, 0xcc, 0xf5, 0x3b, 0x36, 0xf6, 0x0d, 0x1b, 0x1f, 0xfa, 0x3b, 0xd3, 0x6c, 0x98,
	0x4e, 0x9c, 0xfc, 0x60, 0x78, 0x56, 0xd9, 0xbf, 0x58, 0x36, 0xf3, 0xea, 0xe9, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x33, 0x14, 0xe7, 0x1e, 0x1d, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserByCredentials(ctx context.Context, in *GetUserByCredentialsRequest, opts ...grpc.CallOption) (*GetUserByCredentialsResponse, error)
	EmailVerification(ctx context.Context, in *EmailVerificationRequest, opts ...grpc.CallOption) (*EmailVerificationResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByCredentials(ctx context.Context, in *GetUserByCredentialsRequest, opts ...grpc.CallOption) (*GetUserByCredentialsResponse, error) {
	out := new(GetUserByCredentialsResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUserByCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) EmailVerification(ctx context.Context, in *EmailVerificationRequest, opts ...grpc.CallOption) (*EmailVerificationResponse, error) {
	out := new(EmailVerificationResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/EmailVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserByCredentials(context.Context, *GetUserByCredentialsRequest) (*GetUserByCredentialsResponse, error)
	EmailVerification(context.Context, *EmailVerificationRequest) (*EmailVerificationResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserByCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByCredentials(ctx, req.(*GetUserByCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_EmailVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).EmailVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/EmailVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).EmailVerification(ctx, req.(*EmailVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetUserByCredentials",
			Handler:    _UserService_GetUserByCredentials_Handler,
		},
		{
			MethodName: "EmailVerification",
			Handler:    _UserService_EmailVerification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery/grpc/user/user.proto",
}
