// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delivery/grpc/user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender               string               `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ProfilePictureUrl    string               `protobuf:"bytes,9,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	IsVerified           bool                 `protobuf:"varint,10,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	IsSuspended          bool                 `protobuf:"varint,11,opt,name=is_suspended,json=isSuspended,proto3" json:"is_suspended,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetProfilePictureUrl() string {
	if m != nil {
		return m.ProfilePictureUrl
	}
	return ""
}

func (m *User) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *User) GetIsSuspended() bool {
	if m != nil {
		return m.IsSuspended
	}
	return false
}

type CreateUserRequest struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string               `protobuf:"bytes,6,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender               string               `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *CreateUserRequest) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *CreateUserRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *CreateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateUserResponse struct {
	Data                 *CreateUserRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Title                string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Code                 string             `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetData() *CreateUserRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateUserResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateUserResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type EmailVerificationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VerificationToken    string   `protobuf:"bytes,2,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailVerificationRequest) Reset()         { *m = EmailVerificationRequest{} }
func (m *EmailVerificationRequest) String() string { return proto.CompactTextString(m) }
func (*EmailVerificationRequest) ProtoMessage()    {}
func (*EmailVerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{3}
}

func (m *EmailVerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailVerificationRequest.Unmarshal(m, b)
}
func (m *EmailVerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailVerificationRequest.Marshal(b, m, deterministic)
}
func (m *EmailVerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailVerificationRequest.Merge(m, src)
}
func (m *EmailVerificationRequest) XXX_Size() int {
	return xxx_messageInfo_EmailVerificationRequest.Size(m)
}
func (m *EmailVerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailVerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailVerificationRequest proto.InternalMessageInfo

func (m *EmailVerificationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailVerificationRequest) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

type EmailVerificationResponse struct {
	Data                 *EmailVerificationRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Title                string                    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Code                 string                    `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *EmailVerificationResponse) Reset()         { *m = EmailVerificationResponse{} }
func (m *EmailVerificationResponse) String() string { return proto.CompactTextString(m) }
func (*EmailVerificationResponse) ProtoMessage()    {}
func (*EmailVerificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{4}
}

func (m *EmailVerificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailVerificationResponse.Unmarshal(m, b)
}
func (m *EmailVerificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailVerificationResponse.Marshal(b, m, deterministic)
}
func (m *EmailVerificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailVerificationResponse.Merge(m, src)
}
func (m *EmailVerificationResponse) XXX_Size() int {
	return xxx_messageInfo_EmailVerificationResponse.Size(m)
}
func (m *EmailVerificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailVerificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailVerificationResponse proto.InternalMessageInfo

func (m *EmailVerificationResponse) GetData() *EmailVerificationRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EmailVerificationResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EmailVerificationResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ResetPasswordTokenRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordTokenRequest) Reset()         { *m = ResetPasswordTokenRequest{} }
func (m *ResetPasswordTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordTokenRequest) ProtoMessage()    {}
func (*ResetPasswordTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{5}
}

func (m *ResetPasswordTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordTokenRequest.Unmarshal(m, b)
}
func (m *ResetPasswordTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordTokenRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordTokenRequest.Merge(m, src)
}
func (m *ResetPasswordTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordTokenRequest.Size(m)
}
func (m *ResetPasswordTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordTokenRequest proto.InternalMessageInfo

func (m *ResetPasswordTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ResetPasswordTokenResponse struct {
	Data                 *ResetPasswordTokenRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Title                string                     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Code                 string                     `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ResetPasswordTokenResponse) Reset()         { *m = ResetPasswordTokenResponse{} }
func (m *ResetPasswordTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordTokenResponse) ProtoMessage()    {}
func (*ResetPasswordTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{6}
}

func (m *ResetPasswordTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordTokenResponse.Unmarshal(m, b)
}
func (m *ResetPasswordTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordTokenResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordTokenResponse.Merge(m, src)
}
func (m *ResetPasswordTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordTokenResponse.Size(m)
}
func (m *ResetPasswordTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordTokenResponse proto.InternalMessageInfo

func (m *ResetPasswordTokenResponse) GetData() *ResetPasswordTokenRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResetPasswordTokenResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ResetPasswordTokenResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ResetPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ResetPasswordToken   string   `protobuf:"bytes,2,opt,name=reset_password_token,json=resetPasswordToken,proto3" json:"reset_password_token,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string   `protobuf:"bytes,4,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{7}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetPasswordRequest) GetResetPasswordToken() string {
	if m != nil {
		return m.ResetPasswordToken
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetPasswordRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

type ResetPasswordResponse struct {
	Data                 *ResetPasswordRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Title                string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Code                 string                `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{8}
}

func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(m, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

func (m *ResetPasswordResponse) GetData() *ResetPasswordRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResetPasswordResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ResetPasswordResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type UpdateUserRequest struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string               `protobuf:"bytes,6,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender               string               `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ProfilePictureUrl    string               `protobuf:"bytes,10,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{9}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateUserRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *UpdateUserRequest) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *UpdateUserRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UpdateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UpdateUserRequest) GetProfilePictureUrl() string {
	if m != nil {
		return m.ProfilePictureUrl
	}
	return ""
}

type UpdateUserSettingRequest struct {
	UserUid              string                `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	EmailNotification    *wrappers.BoolValue   `protobuf:"bytes,2,opt,name=email_notification,json=emailNotification,proto3" json:"email_notification,omitempty"`
	PushNotification     *wrappers.BoolValue   `protobuf:"bytes,3,opt,name=push_notification,json=pushNotification,proto3" json:"push_notification,omitempty"`
	CurrencyUid          *wrappers.StringValue `protobuf:"bytes,4,opt,name=currency_uid,json=currencyUid,proto3" json:"currency_uid,omitempty"`
	LanguageUid          *wrappers.StringValue `protobuf:"bytes,5,opt,name=language_uid,json=languageUid,proto3" json:"language_uid,omitempty"`
	PaymentTypeUid       *wrappers.StringValue `protobuf:"bytes,6,opt,name=payment_type_uid,json=paymentTypeUid,proto3" json:"payment_type_uid,omitempty"`
	CreditCardNumber     *wrappers.StringValue `protobuf:"bytes,7,opt,name=CreditCardNumber,proto3" json:"CreditCardNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserSettingRequest) Reset()         { *m = UpdateUserSettingRequest{} }
func (m *UpdateUserSettingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserSettingRequest) ProtoMessage()    {}
func (*UpdateUserSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{10}
}

func (m *UpdateUserSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserSettingRequest.Unmarshal(m, b)
}
func (m *UpdateUserSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserSettingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserSettingRequest.Merge(m, src)
}
func (m *UpdateUserSettingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserSettingRequest.Size(m)
}
func (m *UpdateUserSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserSettingRequest proto.InternalMessageInfo

func (m *UpdateUserSettingRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *UpdateUserSettingRequest) GetEmailNotification() *wrappers.BoolValue {
	if m != nil {
		return m.EmailNotification
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetPushNotification() *wrappers.BoolValue {
	if m != nil {
		return m.PushNotification
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetCurrencyUid() *wrappers.StringValue {
	if m != nil {
		return m.CurrencyUid
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetLanguageUid() *wrappers.StringValue {
	if m != nil {
		return m.LanguageUid
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetPaymentTypeUid() *wrappers.StringValue {
	if m != nil {
		return m.PaymentTypeUid
	}
	return nil
}

func (m *UpdateUserSettingRequest) GetCreditCardNumber() *wrappers.StringValue {
	if m != nil {
		return m.CreditCardNumber
	}
	return nil
}

type Filter struct {
	Field                string   `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=Operator,proto3" json:"Operator,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{11}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Filter) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Filter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BrowseRequest struct {
	Filters              []*Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Limit                int32     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32     `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BrowseRequest) Reset()         { *m = BrowseRequest{} }
func (m *BrowseRequest) String() string { return proto.CompactTextString(m) }
func (*BrowseRequest) ProtoMessage()    {}
func (*BrowseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{12}
}

func (m *BrowseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseRequest.Unmarshal(m, b)
}
func (m *BrowseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseRequest.Marshal(b, m, deterministic)
}
func (m *BrowseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseRequest.Merge(m, src)
}
func (m *BrowseRequest) XXX_Size() int {
	return xxx_messageInfo_BrowseRequest.Size(m)
}
func (m *BrowseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseRequest proto.InternalMessageInfo

func (m *BrowseRequest) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *BrowseRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *BrowseRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type UpdateUserResponse struct {
	Data                 *UpdateUserRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Title                string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Code                 string             `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{13}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetData() *UpdateUserRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateUserResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateUserResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type UpdateUserSettingResponse struct {
	Data                 *UpdateUserSettingRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UpdateUserSettingResponse) Reset()         { *m = UpdateUserSettingResponse{} }
func (m *UpdateUserSettingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserSettingResponse) ProtoMessage()    {}
func (*UpdateUserSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{14}
}

func (m *UpdateUserSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserSettingResponse.Unmarshal(m, b)
}
func (m *UpdateUserSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserSettingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserSettingResponse.Merge(m, src)
}
func (m *UpdateUserSettingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserSettingResponse.Size(m)
}
func (m *UpdateUserSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserSettingResponse proto.InternalMessageInfo

func (m *UpdateUserSettingResponse) GetData() *UpdateUserSettingRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

type BrowseUserResponse struct {
	Data                 []*User  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrowseUserResponse) Reset()         { *m = BrowseUserResponse{} }
func (m *BrowseUserResponse) String() string { return proto.CompactTextString(m) }
func (*BrowseUserResponse) ProtoMessage()    {}
func (*BrowseUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{15}
}

func (m *BrowseUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseUserResponse.Unmarshal(m, b)
}
func (m *BrowseUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseUserResponse.Marshal(b, m, deterministic)
}
func (m *BrowseUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseUserResponse.Merge(m, src)
}
func (m *BrowseUserResponse) XXX_Size() int {
	return xxx_messageInfo_BrowseUserResponse.Size(m)
}
func (m *BrowseUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseUserResponse proto.InternalMessageInfo

func (m *BrowseUserResponse) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

type Error struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{16}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Error) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetUserByCredentialsRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByCredentialsRequest) Reset()         { *m = GetUserByCredentialsRequest{} }
func (m *GetUserByCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByCredentialsRequest) ProtoMessage()    {}
func (*GetUserByCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{17}
}

func (m *GetUserByCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByCredentialsRequest.Unmarshal(m, b)
}
func (m *GetUserByCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByCredentialsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByCredentialsRequest.Merge(m, src)
}
func (m *GetUserByCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByCredentialsRequest.Size(m)
}
func (m *GetUserByCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByCredentialsRequest proto.InternalMessageInfo

func (m *GetUserByCredentialsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserByCredentialsRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetUserByCredentialsResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByCredentialsResponse) Reset()         { *m = GetUserByCredentialsResponse{} }
func (m *GetUserByCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByCredentialsResponse) ProtoMessage()    {}
func (*GetUserByCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{18}
}

func (m *GetUserByCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByCredentialsResponse.Unmarshal(m, b)
}
func (m *GetUserByCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByCredentialsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByCredentialsResponse.Merge(m, src)
}
func (m *GetUserByCredentialsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByCredentialsResponse.Size(m)
}
func (m *GetUserByCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByCredentialsResponse proto.InternalMessageInfo

func (m *GetUserByCredentialsResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetUserRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{19}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetUserResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{20}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResendEmailVerificationRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	VerificationToken    string   `protobuf:"bytes,3,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendEmailVerificationRequest) Reset()         { *m = ResendEmailVerificationRequest{} }
func (m *ResendEmailVerificationRequest) String() string { return proto.CompactTextString(m) }
func (*ResendEmailVerificationRequest) ProtoMessage()    {}
func (*ResendEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{21}
}

func (m *ResendEmailVerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendEmailVerificationRequest.Unmarshal(m, b)
}
func (m *ResendEmailVerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendEmailVerificationRequest.Marshal(b, m, deterministic)
}
func (m *ResendEmailVerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendEmailVerificationRequest.Merge(m, src)
}
func (m *ResendEmailVerificationRequest) XXX_Size() int {
	return xxx_messageInfo_ResendEmailVerificationRequest.Size(m)
}
func (m *ResendEmailVerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendEmailVerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResendEmailVerificationRequest proto.InternalMessageInfo

func (m *ResendEmailVerificationRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResendEmailVerificationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResendEmailVerificationRequest) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

type ResendEmailVerificationRespone struct {
	Data                 *ResendEmailVerificationRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 string                          `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title                string                          `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ResendEmailVerificationRespone) Reset()         { *m = ResendEmailVerificationRespone{} }
func (m *ResendEmailVerificationRespone) String() string { return proto.CompactTextString(m) }
func (*ResendEmailVerificationRespone) ProtoMessage()    {}
func (*ResendEmailVerificationRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{22}
}

func (m *ResendEmailVerificationRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendEmailVerificationRespone.Unmarshal(m, b)
}
func (m *ResendEmailVerificationRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendEmailVerificationRespone.Marshal(b, m, deterministic)
}
func (m *ResendEmailVerificationRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendEmailVerificationRespone.Merge(m, src)
}
func (m *ResendEmailVerificationRespone) XXX_Size() int {
	return xxx_messageInfo_ResendEmailVerificationRespone.Size(m)
}
func (m *ResendEmailVerificationRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendEmailVerificationRespone.DiscardUnknown(m)
}

var xxx_messageInfo_ResendEmailVerificationRespone proto.InternalMessageInfo

func (m *ResendEmailVerificationRespone) GetData() *ResendEmailVerificationRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResendEmailVerificationRespone) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResendEmailVerificationRespone) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetUserInfoRespone struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRespone) Reset()         { *m = GetUserInfoRespone{} }
func (m *GetUserInfoRespone) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRespone) ProtoMessage()    {}
func (*GetUserInfoRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{23}
}

func (m *GetUserInfoRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRespone.Unmarshal(m, b)
}
func (m *GetUserInfoRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRespone.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRespone.Merge(m, src)
}
func (m *GetUserInfoRespone) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRespone.Size(m)
}
func (m *GetUserInfoRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRespone.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRespone proto.InternalMessageInfo

func (m *GetUserInfoRespone) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUserInfoRespone) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetUserInfoRespone) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateUserHostRequest struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string               `protobuf:"bytes,6,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender               string               `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	IsVerified           bool                 `protobuf:"varint,10,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	ByAdmin              bool                 `protobuf:"varint,11,opt,name=by_admin,json=byAdmin,proto3" json:"by_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateUserHostRequest) Reset()         { *m = CreateUserHostRequest{} }
func (m *CreateUserHostRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserHostRequest) ProtoMessage()    {}
func (*CreateUserHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{24}
}

func (m *CreateUserHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserHostRequest.Unmarshal(m, b)
}
func (m *CreateUserHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserHostRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserHostRequest.Merge(m, src)
}
func (m *CreateUserHostRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserHostRequest.Size(m)
}
func (m *CreateUserHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserHostRequest proto.InternalMessageInfo

func (m *CreateUserHostRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CreateUserHostRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserHostRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserHostRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserHostRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserHostRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *CreateUserHostRequest) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *CreateUserHostRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *CreateUserHostRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateUserHostRequest) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *CreateUserHostRequest) GetByAdmin() bool {
	if m != nil {
		return m.ByAdmin
	}
	return false
}

type CreateUserHostResponse struct {
	Data                 *CreateUserHostRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title                string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateUserHostResponse) Reset()         { *m = CreateUserHostResponse{} }
func (m *CreateUserHostResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserHostResponse) ProtoMessage()    {}
func (*CreateUserHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce0ae0e1358080f, []int{25}
}

func (m *CreateUserHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserHostResponse.Unmarshal(m, b)
}
func (m *CreateUserHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserHostResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserHostResponse.Merge(m, src)
}
func (m *CreateUserHostResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserHostResponse.Size(m)
}
func (m *CreateUserHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserHostResponse proto.InternalMessageInfo

func (m *CreateUserHostResponse) GetData() *CreateUserHostRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateUserHostResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateUserHostResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.CreateUserResponse")
	proto.RegisterType((*EmailVerificationRequest)(nil), "user.EmailVerificationRequest")
	proto.RegisterType((*EmailVerificationResponse)(nil), "user.EmailVerificationResponse")
	proto.RegisterType((*ResetPasswordTokenRequest)(nil), "user.ResetPasswordTokenRequest")
	proto.RegisterType((*ResetPasswordTokenResponse)(nil), "user.ResetPasswordTokenResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "user.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "user.ResetPasswordResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserSettingRequest)(nil), "user.UpdateUserSettingRequest")
	proto.RegisterType((*Filter)(nil), "user.Filter")
	proto.RegisterType((*BrowseRequest)(nil), "user.BrowseRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "user.UpdateUserResponse")
	proto.RegisterType((*UpdateUserSettingResponse)(nil), "user.UpdateUserSettingResponse")
	proto.RegisterType((*BrowseUserResponse)(nil), "user.BrowseUserResponse")
	proto.RegisterType((*Error)(nil), "user.Error")
	proto.RegisterType((*GetUserByCredentialsRequest)(nil), "user.GetUserByCredentialsRequest")
	proto.RegisterType((*GetUserByCredentialsResponse)(nil), "user.GetUserByCredentialsResponse")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user.GetUserResponse")
	proto.RegisterType((*ResendEmailVerificationRequest)(nil), "user.ResendEmailVerificationRequest")
	proto.RegisterType((*ResendEmailVerificationRespone)(nil), "user.ResendEmailVerificationRespone")
	proto.RegisterType((*GetUserInfoRespone)(nil), "user.GetUserInfoRespone")
	proto.RegisterType((*CreateUserHostRequest)(nil), "user.CreateUserHostRequest")
	proto.RegisterType((*CreateUserHostResponse)(nil), "user.CreateUserHostResponse")
}

func init() { proto.RegisterFile("delivery/grpc/user/user.proto", fileDescriptor_2ce0ae0e1358080f) }

var fileDescriptor_2ce0ae0e1358080f = []byte{
	// 1391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x86, 0x7e, 0x6c, 0xcb, 0x23, 0x3b, 0xb5, 0x36, 0x76, 0x4a, 0xcb, 0x8e, 0xad, 0x2c, 0xd2,
	0xc0, 0x48, 0x50, 0x29, 0x71, 0xda, 0xa0, 0xe8, 0x21, 0x41, 0x6d, 0xe4, 0xef, 0xd0, 0x38, 0x50,
	0xe2, 0x00, 0x3d, 0xb4, 0x04, 0x2d, 0xae, 0xe4, 0x45, 0x28, 0x2e, 0xb3, 0xbb, 0xb4, 0x21, 0x04,
	0x05, 0x8a, 0x36, 0x6f, 0xd0, 0x4b, 0xdf, 0xa2, 0xe8, 0x33, 0xf4, 0x11, 0x7a, 0xee, 0xad, 0x6f,
	0x50, 0xf4, 0x5e, 0xec, 0x72, 0x29, 0x91, 0x26, 0x29, 0xd9, 0xe9, 0xa1, 0x97, 0x5c, 0x0c, 0xed,
	0xce, 0xce, 0x37, 0x33, 0xdf, 0xcc, 0xce, 0x70, 0x0d, 0x57, 0x5d, 0xe2, 0xd1, 0x13, 0xc2, 0x47,
	0x9d, 0x01, 0x0f, 0x7a, 0x9d, 0x50, 0x10, 0xae, 0xff, 0xb4, 0x03, 0xce, 0x24, 0x43, 0x55, 0xf5,
	0xbb, 0xb9, 0x3d, 0x60, 0x6c, 0xe0, 0x91, 0x8e, 0xde, 0x3b, 0x0a, 0xfb, 0x1d, 0x49, 0x87, 0x44,
	0x48, 0x67, 0x18, 0x44, 0xc7, 0x9a, 0x9b, 0xe6, 0x80, 0x13, 0xd0, 0x8e, 0xe3, 0xfb, 0x4c, 0x3a,
	0x92, 0x32, 0x5f, 0x18, 0xe9, 0xd6, 0x59, 0xf5, 0x53, 0xee, 0x04, 0x01, 0xe1, 0x46, 0x8e, 0xff,
	0x29, 0x43, 0xf5, 0x50, 0x10, 0x8e, 0x56, 0xa0, 0x12, 0x52, 0xd7, 0x2a, 0xb5, 0x4a, 0x3b, 0x8b,
	0x5d, 0xf5, 0x13, 0x5d, 0x05, 0xe8, 0x53, 0x2e, 0xa4, 0xed, 0x3b, 0x43, 0x62, 0x95, 0xb5, 0x60,
	0x51, 0xef, 0x3c, 0x73, 0x86, 0x04, 0x6d, 0xc0, 0xa2, 0xe7, 0xc4, 0xd2, 0x8a, 0x96, 0xd6, 0xd4,
	0x86, 0x16, 0xae, 0xc2, 0x1c, 0x19, 0x3a, 0xd4, 0xb3, 0xaa, 0x5a, 0x10, 0x2d, 0x50, 0x13, 0x6a,
	0x81, 0x23, 0xc4, 0x29, 0xe3, 0xae, 0x35, 0x17, 0x69, 0xc4, 0x6b, 0x74, 0x1f, 0x96, 0x5d, 0x47,
	0x12, 0x9b, 0xf5, 0xed, 0x23, 0xca, 0xe5, 0xb1, 0x35, 0xdf, 0x2a, 0xed, 0xd4, 0x77, 0x9b, 0xed,
	0x28, 0x80, 0x76, 0x1c, 0x40, 0xfb, 0x65, 0x1c, 0x7f, 0xb7, 0xae, 0x14, 0x0e, 0xfa, 0x7b, 0xea,
	0x38, 0xba, 0x02, 0xf3, 0x03, 0xe2, 0xbb, 0x84, 0x5b, 0x0b, 0x1a, 0xd9, 0xac, 0xd0, 0x35, 0x58,
	0x0a, 0x8e, 0x99, 0x4f, 0x6c, 0x3f, 0x1c, 0x1e, 0x11, 0x6e, 0xd5, 0xb4, 0xb4, 0xae, 0xf7, 0x9e,
	0xe9, 0x2d, 0xd4, 0x86, 0xcb, 0x01, 0x67, 0x7d, 0xea, 0x11, 0x3b, 0xa0, 0x3d, 0x19, 0x72, 0x62,
	0x87, 0xdc, 0xb3, 0x16, 0xf5, 0xc9, 0x86, 0x11, 0x3d, 0x8f, 0x24, 0x87, 0xdc, 0x43, 0xdb, 0x50,
	0xa7, 0xc2, 0x3e, 0x21, 0x9c, 0xf6, 0x29, 0x71, 0x2d, 0x68, 0x95, 0x76, 0x6a, 0x5d, 0xa0, 0xe2,
	0x95, 0xd9, 0x51, 0x36, 0xa9, 0xb0, 0x45, 0x28, 0x02, 0xe5, 0x83, 0x6b, 0xd5, 0xf5, 0x89, 0x3a,
	0x15, 0x2f, 0xe2, 0x2d, 0xfc, 0x7b, 0x19, 0x1a, 0xfb, 0x9c, 0x38, 0x92, 0x28, 0xf6, 0xbb, 0xe4,
	0x4d, 0x48, 0x84, 0xfc, 0xdf, 0x93, 0x70, 0x17, 0xd6, 0xe2, 0xdf, 0x76, 0x8f, 0xf9, 0x7d, 0xca,
	0x87, 0xba, 0x9a, 0x74, 0x32, 0x16, 0xbb, 0xab, 0xb1, 0x70, 0x3f, 0x21, 0xcb, 0x66, 0x6e, 0xe1,
	0x7d, 0x33, 0x57, 0x9b, 0x9a, 0xb9, 0xc5, 0x4c, 0xe6, 0xf0, 0x6b, 0x40, 0x49, 0x12, 0x45, 0xc0,
	0x7c, 0x41, 0xd0, 0x2d, 0xa8, 0xba, 0x8e, 0x74, 0x34, 0x8d, 0xf5, 0xdd, 0x8f, 0xdb, 0xfa, 0x4e,
	0x65, 0xc8, 0xee, 0xea, 0x43, 0x8a, 0x24, 0x49, 0xa5, 0x17, 0x73, 0x1b, 0x2d, 0x10, 0x82, 0x6a,
	0x8f, 0xb9, 0x31, 0xa5, 0xfa, 0x37, 0xb6, 0xc1, 0x7a, 0xa8, 0x18, 0x8c, 0xd2, 0xdc, 0xd3, 0xc1,
	0xc7, 0x89, 0x1b, 0x53, 0x5d, 0x4a, 0x52, 0xfd, 0x29, 0xa0, 0x93, 0xc4, 0x61, 0x5b, 0xb2, 0xd7,
	0xc4, 0x37, 0x86, 0x1a, 0x49, 0xc9, 0x4b, 0x25, 0xc0, 0x23, 0x58, 0xcf, 0x31, 0x60, 0x82, 0xda,
	0x4d, 0x05, 0xb5, 0x15, 0x05, 0x55, 0xe4, 0xcf, 0x85, 0x63, 0xbb, 0x03, 0xeb, 0x5d, 0x22, 0x88,
	0x7c, 0x6e, 0x12, 0xac, 0x1d, 0x9a, 0x1a, 0x1c, 0x7e, 0x0b, 0xcd, 0x3c, 0x15, 0xe3, 0xee, 0xdd,
	0x94, 0xbb, 0xdb, 0x91, 0xbb, 0x85, 0x26, 0x2e, 0xec, 0xef, 0xaf, 0x25, 0x58, 0x4d, 0xa1, 0x4d,
	0x4f, 0xc4, 0x6d, 0x58, 0xe5, 0xea, 0xb4, 0x3d, 0xae, 0xee, 0x64, 0x2a, 0x10, 0xcf, 0xf8, 0x95,
	0xba, 0x25, 0x95, 0xf3, 0xde, 0x92, 0x6a, 0xf1, 0x2d, 0xc1, 0x6f, 0x60, 0xed, 0x8c, 0xc3, 0x86,
	0xa9, 0x76, 0x8a, 0xa9, 0x66, 0x0e, 0x53, 0xef, 0x4b, 0xd2, 0xdf, 0x65, 0x68, 0x1c, 0x06, 0xee,
	0x87, 0x1e, 0xf3, 0x5f, 0x7a, 0x4c, 0xd1, 0x74, 0x80, 0x82, 0xe9, 0x80, 0xff, 0xac, 0x80, 0x35,
	0x61, 0xfd, 0x05, 0x91, 0x92, 0xfa, 0x83, 0x98, 0xfc, 0x75, 0xa8, 0xa9, 0xfc, 0xda, 0x93, 0x0c,
	0x2c, 0xa8, 0xf5, 0x21, 0x75, 0xd1, 0x53, 0x40, 0x9a, 0x3c, 0xdb, 0x67, 0x72, 0x7c, 0x9f, 0x75,
	0x36, 0xf2, 0xe2, 0xdc, 0x63, 0xcc, 0x7b, 0xe5, 0x78, 0x21, 0xe9, 0x36, 0xb4, 0xd6, 0xb3, 0x84,
	0x12, 0x7a, 0x0c, 0x8d, 0x20, 0x14, 0xc7, 0x69, 0xa4, 0xca, 0x4c, 0xa4, 0x15, 0xa5, 0x94, 0x02,
	0x7a, 0x00, 0x4b, 0xbd, 0x90, 0x73, 0xe2, 0xf7, 0x46, 0xda, 0xe5, 0xaa, 0xc6, 0xd8, 0xcc, 0x60,
	0xbc, 0x90, 0x9c, 0xfa, 0x83, 0x08, 0xa5, 0x1e, 0x6b, 0xa8, 0xa0, 0x1e, 0xc0, 0x92, 0xe7, 0xf8,
	0x83, 0xd0, 0x19, 0x10, 0x0d, 0x30, 0x77, 0x1e, 0x80, 0x58, 0x43, 0x01, 0x3c, 0x82, 0x95, 0xc0,
	0x19, 0x0d, 0x89, 0x2f, 0x6d, 0x39, 0x0a, 0x22, 0x90, 0xf9, 0x73, 0x80, 0x5c, 0x32, 0x5a, 0x2f,
	0x47, 0x81, 0xc6, 0x79, 0x02, 0x2b, 0xfb, 0x9c, 0xb8, 0x54, 0xee, 0x3b, 0xdc, 0x8d, 0x32, 0x6b,
	0x6a, 0x68, 0x3a, 0x4e, 0x46, 0x0b, 0x3f, 0x87, 0xf9, 0x47, 0xd4, 0x93, 0x84, 0xab, 0xda, 0x7f,
	0x44, 0x89, 0x17, 0x67, 0x32, 0x5a, 0xa8, 0xda, 0x3f, 0x08, 0x08, 0x77, 0x24, 0xe3, 0xe6, 0x2e,
	0x8d, 0xd7, 0x4a, 0x43, 0xc3, 0x9a, 0x6b, 0x14, 0x2d, 0x30, 0x81, 0xe5, 0x3d, 0xce, 0x4e, 0x05,
	0x89, 0xab, 0xe4, 0x06, 0x2c, 0xf4, 0xb5, 0x09, 0x61, 0x95, 0x5a, 0x95, 0x9d, 0xfa, 0xee, 0x52,
	0xd4, 0x15, 0x22, 0xbb, 0xdd, 0x58, 0xa8, 0xe0, 0x3c, 0x3a, 0xa4, 0x52, 0xdb, 0x99, 0xeb, 0x46,
	0x0b, 0x55, 0xeb, 0xac, 0xdf, 0x17, 0x44, 0x6a, 0x2b, 0x73, 0x5d, 0xb3, 0x52, 0xc3, 0x32, 0xd9,
	0x0d, 0xa6, 0x0d, 0xcb, 0x4c, 0xd7, 0xb8, 0x70, 0xef, 0x39, 0x80, 0xf5, 0x9c, 0x4b, 0x30, 0x6d,
	0x96, 0x15, 0xdd, 0x99, 0xc8, 0x34, 0xfe, 0x0c, 0x50, 0x44, 0x52, 0xca, 0xfb, 0xad, 0x31, 0x92,
	0xa2, 0x09, 0x0c, 0x92, 0x3a, 0x11, 0x69, 0x7d, 0x0e, 0x73, 0x0f, 0x39, 0x67, 0x5c, 0x91, 0x22,
	0x58, 0xc8, 0x7b, 0xc4, 0x24, 0xcb, 0xac, 0xf2, 0x23, 0xc2, 0x07, 0xb0, 0xf1, 0x98, 0x48, 0x85,
	0xb3, 0x37, 0x52, 0x05, 0x40, 0x7c, 0x49, 0x1d, 0x4f, 0x4c, 0x1f, 0x32, 0xc9, 0xa6, 0x57, 0x4e,
	0x37, 0x3d, 0x7c, 0x1f, 0x36, 0xf3, 0x01, 0x33, 0x71, 0x94, 0x72, 0xe3, 0xc0, 0x70, 0xc9, 0xe8,
	0x17, 0xb6, 0x71, 0x7c, 0x07, 0x3e, 0x1a, 0x9f, 0x39, 0x27, 0xec, 0x29, 0x6c, 0xa9, 0x49, 0xe3,
	0xbb, 0x85, 0x1f, 0x36, 0xd9, 0x69, 0x31, 0x0e, 0xbe, 0x3c, 0xfb, 0x53, 0xa7, 0x52, 0xf4, 0xa9,
	0xf3, 0xae, 0x34, 0xc5, 0xb2, 0x72, 0x9e, 0xa0, 0x2f, 0x52, 0xbe, 0x5f, 0x9f, 0xcc, 0xc5, 0x62,
	0x6f, 0x4d, 0x95, 0xc6, 0xf5, 0x58, 0x9e, 0xd4, 0xe3, 0x24, 0xcf, 0x95, 0x64, 0x9e, 0xbf, 0x03,
	0x64, 0x28, 0x7b, 0xea, 0xf7, 0x59, 0x6c, 0x79, 0x06, 0x6b, 0x17, 0xc0, 0xff, 0xa9, 0x02, 0x6b,
	0x93, 0x0f, 0xcf, 0x27, 0x4c, 0xc8, 0x0f, 0x53, 0xf8, 0xfd, 0xa6, 0xf0, 0xcc, 0x37, 0xd7, 0x3a,
	0xd4, 0x8e, 0x46, 0xb6, 0xe3, 0x0e, 0xa9, 0x6f, 0xde, 0x5b, 0x0b, 0x47, 0xa3, 0xaf, 0xd4, 0x12,
	0x0b, 0xb8, 0x72, 0x36, 0x09, 0xe6, 0x7e, 0x74, 0x52, 0x99, 0xde, 0x38, 0xfb, 0x52, 0x48, 0x24,
	0xec, 0xa2, 0xa9, 0xdf, 0xfd, 0xad, 0x06, 0xf5, 0xa8, 0x99, 0xf1, 0x13, 0xda, 0x23, 0xe8, 0x1b,
	0x80, 0x09, 0x30, 0x2a, 0x7a, 0x94, 0x34, 0xad, 0xac, 0x20, 0xf2, 0x15, 0x5b, 0x3f, 0xfe, 0xf1,
	0xd7, 0xcf, 0x65, 0x84, 0x97, 0xf5, 0x4b, 0xff, 0xe4, 0x8e, 0xfe, 0x57, 0x81, 0xf8, 0xb2, 0x74,
	0x13, 0x7d, 0x0d, 0xf5, 0x44, 0x15, 0xa3, 0x44, 0xc1, 0xc6, 0x70, 0xd9, 0x22, 0x8f, 0xe1, 0xd0,
	0x4a, 0x0a, 0xae, 0x33, 0x24, 0xc8, 0x06, 0x98, 0xf4, 0x62, 0x54, 0x34, 0x11, 0x62, 0xe8, 0xec,
	0x48, 0xc1, 0x5b, 0x1a, 0xda, 0xda, 0xbd, 0x9c, 0x86, 0x7e, 0x1b, 0x52, 0xf7, 0x7b, 0xe5, 0xef,
	0x3d, 0x58, 0x30, 0x0e, 0xa1, 0xd5, 0x94, 0x7f, 0x31, 0xf4, 0xda, 0x99, 0x5d, 0x93, 0xad, 0x6f,
	0x61, 0x35, 0xaf, 0x89, 0xa2, 0x6b, 0xa9, 0xe3, 0x79, 0x1d, 0xbb, 0x89, 0xa7, 0x1d, 0x31, 0xf0,
	0x3f, 0x94, 0xa0, 0x91, 0xe9, 0x2c, 0x68, 0xc6, 0x4b, 0xab, 0xb9, 0x5d, 0x28, 0x37, 0x6c, 0xdc,
	0xd4, 0x6c, 0x5c, 0xc7, 0xdb, 0x69, 0x36, 0xf4, 0x15, 0x4d, 0x36, 0x46, 0xc5, 0xcc, 0x2f, 0x25,
	0x40, 0x51, 0x8b, 0x4b, 0xf9, 0x70, 0xae, 0xe6, 0xd7, 0x9c, 0x75, 0x2a, 0xca, 0xfb, 0x3d, 0xed,
	0xce, 0x6d, 0x7c, 0x2b, 0x27, 0x39, 0x1d, 0xae, 0x75, 0x73, 0x5d, 0x7b, 0x67, 0x5c, 0x3b, 0xf3,
	0x4e, 0x9a, 0xf5, 0xb2, 0x6b, 0xb6, 0x8a, 0x0f, 0x18, 0x82, 0x6e, 0x69, 0x8f, 0x3e, 0xc1, 0xad,
	0xb4, 0x47, 0xfa, 0x51, 0x16, 0xb7, 0x21, 0x3d, 0x4e, 0x94, 0x1b, 0x01, 0x2c, 0xa7, 0xa0, 0xd0,
	0x94, 0x07, 0x53, 0x73, 0x23, 0x57, 0x66, 0xcc, 0xde, 0xd0, 0x66, 0x5b, 0x78, 0x63, 0x8a, 0x59,
	0x65, 0x91, 0xc2, 0xa5, 0x74, 0x47, 0x40, 0xd3, 0xfa, 0x44, 0x73, 0x33, 0x5f, 0x68, 0x8c, 0x6e,
	0x6a, 0xa3, 0x57, 0x70, 0x23, 0x69, 0xf4, 0x98, 0x09, 0xa9, 0x2e, 0xf2, 0xd1, 0xbc, 0x6e, 0xa0,
	0x77, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x73, 0x52, 0x19, 0x19, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUserInfo(ctx context.Context, in *User, opts ...grpc.CallOption) (*GetUserInfoRespone, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserByCredentials(ctx context.Context, in *GetUserByCredentialsRequest, opts ...grpc.CallOption) (*GetUserByCredentialsResponse, error)
	EmailVerification(ctx context.Context, in *EmailVerificationRequest, opts ...grpc.CallOption) (*EmailVerificationResponse, error)
	ResendVerification(ctx context.Context, in *ResendEmailVerificationRequest, opts ...grpc.CallOption) (*ResendEmailVerificationRespone, error)
	ResetPasswordToken(ctx context.Context, in *ResetPasswordTokenRequest, opts ...grpc.CallOption) (*ResetPasswordTokenResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
	CreateUserHost(ctx context.Context, in *CreateUserHostRequest, opts ...grpc.CallOption) (*CreateUserHostResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *User, opts ...grpc.CallOption) (*GetUserInfoRespone, error) {
	out := new(GetUserInfoRespone)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByCredentials(ctx context.Context, in *GetUserByCredentialsRequest, opts ...grpc.CallOption) (*GetUserByCredentialsResponse, error) {
	out := new(GetUserByCredentialsResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUserByCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) EmailVerification(ctx context.Context, in *EmailVerificationRequest, opts ...grpc.CallOption) (*EmailVerificationResponse, error) {
	out := new(EmailVerificationResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/EmailVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResendVerification(ctx context.Context, in *ResendEmailVerificationRequest, opts ...grpc.CallOption) (*ResendEmailVerificationRespone, error) {
	out := new(ResendEmailVerificationRespone)
	err := c.cc.Invoke(ctx, "/user.UserService/ResendVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetPasswordToken(ctx context.Context, in *ResetPasswordTokenRequest, opts ...grpc.CallOption) (*ResetPasswordTokenResponse, error) {
	out := new(ResetPasswordTokenResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/ResetPasswordToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUserHost(ctx context.Context, in *CreateUserHostRequest, opts ...grpc.CallOption) (*CreateUserHostResponse, error) {
	out := new(CreateUserHostResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUserHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUserInfo(context.Context, *User) (*GetUserInfoRespone, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserByCredentials(context.Context, *GetUserByCredentialsRequest) (*GetUserByCredentialsResponse, error)
	EmailVerification(context.Context, *EmailVerificationRequest) (*EmailVerificationResponse, error)
	ResendVerification(context.Context, *ResendEmailVerificationRequest) (*ResendEmailVerificationRespone, error)
	ResetPasswordToken(context.Context, *ResetPasswordTokenRequest) (*ResetPasswordTokenResponse, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	CreateUserHost(context.Context, *CreateUserHostRequest) (*CreateUserHostResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUserInfo(ctx context.Context, req *User) (*GetUserInfoRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUserByCredentials(ctx context.Context, req *GetUserByCredentialsRequest) (*GetUserByCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByCredentials not implemented")
}
func (*UnimplementedUserServiceServer) EmailVerification(ctx context.Context, req *EmailVerificationRequest) (*EmailVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailVerification not implemented")
}
func (*UnimplementedUserServiceServer) ResendVerification(ctx context.Context, req *ResendEmailVerificationRequest) (*ResendEmailVerificationRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendVerification not implemented")
}
func (*UnimplementedUserServiceServer) ResetPasswordToken(ctx context.Context, req *ResetPasswordTokenRequest) (*ResetPasswordTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPasswordToken not implemented")
}
func (*UnimplementedUserServiceServer) ResetPassword(ctx context.Context, req *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (*UnimplementedUserServiceServer) CreateUserHost(ctx context.Context, req *CreateUserHostRequest) (*CreateUserHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserHost not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserByCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByCredentials(ctx, req.(*GetUserByCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_EmailVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).EmailVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/EmailVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).EmailVerification(ctx, req.(*EmailVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResendVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendEmailVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResendVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ResendVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResendVerification(ctx, req.(*ResendEmailVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResetPasswordToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResetPasswordToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ResetPasswordToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetPasswordToken(ctx, req.(*ResetPasswordTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUserHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUserHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUserHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUserHost(ctx, req.(*CreateUserHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetUserByCredentials",
			Handler:    _UserService_GetUserByCredentials_Handler,
		},
		{
			MethodName: "EmailVerification",
			Handler:    _UserService_EmailVerification_Handler,
		},
		{
			MethodName: "ResendVerification",
			Handler:    _UserService_ResendVerification_Handler,
		},
		{
			MethodName: "ResetPasswordToken",
			Handler:    _UserService_ResetPasswordToken_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserService_ResetPassword_Handler,
		},
		{
			MethodName: "CreateUserHost",
			Handler:    _UserService_CreateUserHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery/grpc/user/user.proto",
}
