name: lokaven-action

on: 
  push: 
    branches:
      - master

jobs:
  lokaven-action:
    runs-on: ubuntu-18.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13.x'
      
      - name: Starting Slack Notification
        uses: act10ns/slack@v1
        with:
          status: updated
        if: always()
          